INSERT ALL
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (117870936, 2, 1, 30, 'TEC', 'KENNETH', 'DARÍO', 'SÁNCHEZ', 'OCAMPO', TO_DATE('06/SEP/00', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (123456789, 2, 2, 29, 'TEC', 'FRANCISCO', 'ALONSO', 'BADILLA' ,'FONSECA', TO_DATE('13/MAY/00', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (108080245, 1, 3, 1, 'INS', 'ESTHER', '' ,'MARTINEZ', 'GONZALEZ', TO_DATE('18/SEP/99', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (183719413, 3, 4, 2, 'CCSS', 'ALEX', '','CHAVARRIA' ,'JARAMILLO', TO_DATE('16/OCT/86', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (405912834, 1, 5, 3, 'MCDONALDS', 'SARAH', '', 'CASCANTE' ,'AGUILAR', TO_DATE('2/JUN/75', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (583718913, 1, 6, 4, 'ICE', 'SANDRA', 'MARIA', 'ESPINOSA' ,'BLANCO', TO_DATE('23/AUG/84', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (718271381, 2, 7, 5, '', 'JAIME', 'JAVIER', 'JARAMILLO', 'JIMENEZ', TO_DATE('13/FEB/00', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (573820491, 2, 8, 6, 'UCR', 'BRYAN', '', 'MARCELL', 'RAMIREZ', TO_DATE('15/SEP/97', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (294182913, 1, 9, 7, 'UCR', 'SANDY', '', 'SALGADO', 'ARIAS', TO_DATE('23/MAY/49', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (381823103, 2, 10, 8, 'TEC', 'MAURICIO', 'ESTEBAN', 'ARIAS', 'SANCHEZ', TO_DATE('15/AUG/00', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (319913929, 2, 11, 9, '', 'MARCO', 'EUGENIO', 'PERAZA', 'GUTIERREZ', TO_DATE('6/JAN/88', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (681721841, 1, 12, 10, '', 'SOFIA', '', 'MARIN', 'SUAREZ', TO_DATE('5/DEC/95', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (192193813, 2, 13, 11, '', 'ANUEL', '', 'AGUILAR', 'AMADOR', TO_DATE('5/MAR/96', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (218491823, 1, 14, 12, 'TEC', 'ERICKA', 'SOFIA', 'MARQUEZ' ,'GARCIA', TO_DATE('20/SEP/84', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (693713917, 1, 15, 13, '', 'LUCIA', '', 'BONILLA' ,'GONZALEZ', TO_DATE('25/OCT/01', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (138182911, 2, 16, 14, 'UCR', 'DANIEL', 'JESUS', 'CASTRO', 'ZARATE', TO_DATE('24/OCT/01', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (139137912, 2, 17, 15, 'TEC', 'JOSE', 'JOAQUIN', 'CAMPOS', 'ZELEDON', TO_DATE('13/MAY/00', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (219318319, 2, 18, 16, '', 'JOSE', 'DAVID', 'DELGADO', 'VARGAS', TO_DATE('07/MAR/97', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (182138919, 1, 19, 17, '', 'ESTEFANIA', '', 'HERNANDEZ', 'VINDAS', TO_DATE('27/APR/00', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (374910193, 1, 20, 18, '', 'EYLEEN', '', 'AJUN', 'GUTIERREZ', TO_DATE('21/MAR/56', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (130102101, 2, 21, 19, '', 'JULIO', 'ANDRES', 'VILCHEZ', 'CASTRO', TO_DATE('19/OCT/00', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (121839149, 2, 22, 20, '', 'TIMON', '', 'CONZELMANN', 'RUBIER', TO_DATE('19/MAR/95', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (132891390, 1, 23, 21, '', 'ESTHER', 'DANIELA', 'QUESADA', 'MORALES', TO_DATE('10/OCT/78', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (389274919, 2, 24, 22, 'TEC', 'MARC', '', 'DELGADO', 'MORALES', TO_DATE('10/OCT/99', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (140329302, 2, 25, 23, '', 'ROY', 'DANIEL', 'CAMACHO', 'AZOFEIFA', TO_DATE('10/NOV/78', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (740319201, 2, 26, 24, 'UCR', 'ISAAC', 'FELIPE', 'ARGUEDAS', 'LEON', TO_DATE('10/NOV/78', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (319132910, 1, 27, 25, '', 'MARIANA', '', 'VARELA', 'OCHOA', TO_DATE('31/DEC/66', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (673718123, 1, 28, 26, '', 'ESPERANZA', '', 'ARGUEDAS', 'QUESADA', TO_DATE('11/AUG/99', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (319093021, 2, 29, 27, '', 'REYFORTH', 'EUGENIO', 'MARTINEZ', 'MEJIAS', TO_DATE('10/MAR/88', 'DD/MM/YY'))
    INTO person(citizenship_id, gender_id, address_id, user_id, institution, first_name, middle_name, last_name, secondlast_name, birth_date) 
    VALUES (593482911, 2, 30, 28, '', 'IVAN', '', 'IVANCOVICH', 'MORA', TO_DATE('10/SEP/88', 'DD/MM/YY'))
SELECT * FROM DUAL;