INSERT ALL
    INTO address (community_id, description_) VALUES (4010106, '100 MTS SUR DEL MAXIPALI, CASA VERDE')
    INTO address (community_id, description_) VALUES (4010201, '500 MTS ESTE DE LA PARADA JUNTO AL MERCADO')
    INTO address (community_id, description_) VALUES (3080206, 'CASA SIN PORTÓN FRENTE LA ESCUELA')
    INTO address (community_id, description_) VALUES (4010201, 'CASA DE PORTÓN BLANCA DETRÁS DEL CENTRO COMERCIAL')
    INTO address (community_id, description_) VALUES (4010201, 'CASA 53 RESIDENCIAL MONTE VERDE')
    INTO address (community_id, description_) VALUES (1190174, 'CASA VIEJA AZUL, 50 MTS NORTE DE LA COMISARIA')
    INTO address (community_id, description_) VALUES (1190317, '40 MTS ESTE 100 MTS SUR DEL SÚPER LA AMISTAD, CASA ROJA')
    INTO address (community_id, description_) VALUES (3010308, 'CASA VERDE, CALLEJON SIN SALIDA A 30 METROS DEL PARQUE')
    INTO address (community_id, description_) VALUES (3020503, '100 NORTE METROS DEL VERDUGO ESQUINERO, PORTONES GRISES')
    INTO address (community_id, description_) VALUES (5010102, 'FRENTE AL REFUGIO DE ANIMALES')
    INTO address (community_id, description_) VALUES (5020142, 'APARTAMENTOS VISTA ALTAS, NÚMERO 83')
    INTO address (community_id, description_) VALUES (3040317, '100 MTS OESTE DE LA ESTACIÓN DE BOMBEROS')
    INTO address (community_id, description_) VALUES (6070125, 'CASA ESQUINERA DE COLOR CAFÉ, FRENTE A LA IGLESIA')
    INTO address (community_id, description_) VALUES (6070132, '50 MTS ESTE SUR DEL BAR LA GUARIA, CASA SIN PORTÓN')
    INTO address (community_id, description_) VALUES (3080223, '600 MTS SUR, 40 MTS NORTE DEL CENTRO COMERCIAL, PORTÓN BLANCO')
    INTO address (community_id, description_) VALUES (3080223, '40 MTS ESTE, 100 MTS SUR DEL ESTADIO, CASA AMARILLA')
    INTO address (community_id, description_) VALUES (7060507, 'FINCA LOS REYES, 2KM NORTE DE LA IGLESIA')
    INTO address (community_id, description_) VALUES (7060403, 'RESIDENCIAL LAS CRUCES, CASA NÚMERO 54')
    INTO address (community_id, description_) VALUES (7060405, '400 MTS SUR, 500 MTS ESTE DEL BAJO')
    INTO address (community_id, description_) VALUES (5090611, '1 KM AL SUR DEL PARQUE, FINCA EL ÁGUILA')
    INTO address (community_id, description_) VALUES (5090619, '70 MTS ESTE DE LA PARRILLITA DE PEPE, CASA DE PORTÓN CELESTE')
    INTO address (community_id, description_) VALUES (5100112, 'CASA CONTIGUA A LA ESCUELA')
    INTO address (community_id, description_) VALUES (6010427, '500 MTS ESTE DEL COLEGIO VICENTE FERNANDEZ, CASA BLANCA')
    INTO address (community_id, description_) VALUES (6010429, '500 MTS SUR DE LA BOMBA FRENTE A LA MARISQUERÍA')
    INTO address (community_id, description_) VALUES (6010433, 'VIVIENDA ARRIBA DE LA PANADERÍA GRANO DE ORO')
    INTO address (community_id, description_) VALUES (4010203, 'DETRÁS DE LA COMISARÍA, CASA ROJA')
    INTO address (community_id, description_) VALUES (4010301, 'CASA CAFÉ A 100 MTS DE SALIDA DE LA CALLE PRINCIPAL')
    INTO address (community_id, description_) VALUES (4020206, 'CASA DE ADOBE ESQUINERA, 100 MTS DEL COLEGIO')
    INTO address (community_id, description_) VALUES (1190161, 'CASA VERDE, 100 MTS DEL GIMNASIO SPORT GYM')
    INTO address (community_id, description_) VALUES (1190211, 'APARTAMENTO ARRIBA DE LA PIZZERÍA DIGIORNO')
SELECT * FROM DUAL;