INSERT ALL
   INTO canton(id, province_id, name) VALUES (610, 6, 'CORREDORES')
   INTO canton(id, province_id, name) VALUES (607, 6, 'GOLFITO')
   INTO canton(id, province_id, name) VALUES (608, 6, 'COTO BRUS')
   INTO canton(id, province_id, name) VALUES (605, 6, 'OSA')
   INTO canton(id, province_id, name) VALUES (603, 6, 'BUENOS AIRES')
   INTO canton(id, province_id, name) VALUES (119, 1, 'PEREZ ZELEDON')
   INTO canton(id, province_id, name) VALUES (606, 6, 'QUEPOS')
   INTO canton(id, province_id, name) VALUES (704, 7, 'TALAMANCA')
   INTO canton(id, province_id, name) VALUES (609, 6, 'PARRITA')
   INTO canton(id, province_id, name) VALUES (105, 1, 'TARRAZU')
   INTO canton(id, province_id, name) VALUES (117, 1, 'DOTA')
   INTO canton(id, province_id, name) VALUES (611, 6, 'GARABITO')
   INTO canton(id, province_id, name) VALUES (120, 1, 'LEON CORTES CASTRO')
   INTO canton(id, province_id, name) VALUES (104, 1, 'PURISCAL')
   INTO canton(id, province_id, name) VALUES (106, 1, 'ASERRI')
   INTO canton(id, province_id, name) VALUES (103, 1, 'DESAMPARADOS')
   INTO canton(id, province_id, name) VALUES (112, 1, 'ACOSTA')
   INTO canton(id, province_id, name) VALUES (116, 1, 'TURRUBARES')
   INTO canton(id, province_id, name) VALUES (308, 3, 'EL GUARCO')
   INTO canton(id, province_id, name) VALUES (301, 3, 'CARTAGO')
   INTO canton(id, province_id, name) VALUES (601, 6, 'PUNTARENAS')
   INTO canton(id, province_id, name) VALUES (302, 3, 'PARAISO')
   INTO canton(id, province_id, name) VALUES (304, 3, 'JIMENEZ')
   INTO canton(id, province_id, name) VALUES (305, 3, 'TURRIALBA')
   INTO canton(id, province_id, name) VALUES (107, 1, 'MORA')
   INTO canton(id, province_id, name) VALUES (307, 3, 'OREAMUNO')
   INTO canton(id, province_id, name) VALUES (110, 1, 'ALAJUELITA')
   INTO canton(id, province_id, name) VALUES (701, 7, 'LIMON')
   INTO canton(id, province_id, name) VALUES (303, 3, 'LA UNION')
   INTO canton(id, province_id, name) VALUES (118, 1, 'CURRIDABAT')
   INTO canton(id, province_id, name) VALUES (209, 2, 'OROTINA')
   INTO canton(id, province_id, name) VALUES (101, 1, 'SAN JOSE')
   INTO canton(id, province_id, name) VALUES (102, 1, 'ESCAZU')
   INTO canton(id, province_id, name) VALUES (306, 3, 'ALVARADO')
   INTO canton(id, province_id, name) VALUES (109, 1, 'SANTA ANA')
   INTO canton(id, province_id, name) VALUES (509, 5, 'NANDAYURE')
   INTO canton(id, province_id, name) VALUES (115, 1, 'MONTES DE OCA')
   INTO canton(id, province_id, name) VALUES (108, 1, 'GOICOECHEA')
   INTO canton(id, province_id, name) VALUES (113, 1, 'TIBAS')
   INTO canton(id, province_id, name) VALUES (204, 2, 'SAN MATEO')
   INTO canton(id, province_id, name) VALUES (502, 5, 'NICOYA')
   INTO canton(id, province_id, name) VALUES (205, 2, 'ATENAS')
   INTO canton(id, province_id, name) VALUES (201, 2, 'ALAJUELA')
   INTO canton(id, province_id, name) VALUES (114, 1, 'MORAVIA')
   INTO canton(id, province_id, name) VALUES (602, 6, 'ESPARZA')
   INTO canton(id, province_id, name) VALUES (111, 1, 'VAZQUEZ DE CORONADO')
   INTO canton(id, province_id, name) VALUES (403, 4, 'SANTO DOMINGO')
   INTO canton(id, province_id, name) VALUES (407, 4, 'BELEN')
   INTO canton(id, province_id, name) VALUES (401, 4, 'HEREDIA')
   INTO canton(id, province_id, name) VALUES (409, 4, 'SAN PABLO')
   INTO canton(id, province_id, name) VALUES (202, 2, 'SAN RAMON')
   INTO canton(id, province_id, name) VALUES (511, 5, 'HOJANCHA')
   INTO canton(id, province_id, name) VALUES (408, 4, 'FLORES')
   INTO canton(id, province_id, name) VALUES (405, 4, 'SAN RAFAEL')
   INTO canton(id, province_id, name) VALUES (402, 4, 'BARVA')
   INTO canton(id, province_id, name) VALUES (406, 4, 'SAN ISIDRO')
   INTO canton(id, province_id, name) VALUES (404, 4, 'SANTA BARBARA')
   INTO canton(id, province_id, name) VALUES (207, 2, 'PALMARES')
   INTO canton(id, province_id, name) VALUES (208, 2, 'POAS')
   INTO canton(id, province_id, name) VALUES (203, 2, 'GRECIA')
   INTO canton(id, province_id, name) VALUES (206, 2, 'NARANJO')
   INTO canton(id, province_id, name) VALUES (604, 6, 'MONTES DE ORO')
   INTO canton(id, province_id, name) VALUES (212, 2, 'VALVERDE VEGA')
   INTO canton(id, province_id, name) VALUES (703, 7, 'SIQUIRRES')
   INTO canton(id, province_id, name) VALUES (705, 7, 'MATINA')
   INTO canton(id, province_id, name) VALUES (503, 5, 'SANTA CRUZ')
   INTO canton(id, province_id, name) VALUES (211, 2, 'ZARCERO')
   INTO canton(id, province_id, name) VALUES (706, 7, 'GUACIMO')
   INTO canton(id, province_id, name) VALUES (507, 5, 'ABANGARES')
   INTO canton(id, province_id, name) VALUES (702, 7, 'POCOCI')
   INTO canton(id, province_id, name) VALUES (210, 2, 'SAN CARLOS')
   INTO canton(id, province_id, name) VALUES (506, 5, 'CAÑAS')
   INTO canton(id, province_id, name) VALUES (508, 5, 'TILARAN')
   INTO canton(id, province_id, name) VALUES (410, 4, 'SARAPIQUI')
   INTO canton(id, province_id, name) VALUES (505, 5, 'CARRILLO')
   INTO canton(id, province_id, name) VALUES (216, 2, 'RIO CUARTO')
   INTO canton(id, province_id, name) VALUES (504, 5, 'BAGACES')
   INTO canton(id, province_id, name) VALUES (215, 2, 'GUATUSO')
   INTO canton(id, province_id, name) VALUES (214, 2, 'LOS CHILES')
   INTO canton(id, province_id, name) VALUES (501, 5, 'LIBERIA')
   INTO canton(id, province_id, name) VALUES (213, 2, 'UPALA')
   INTO canton(id, province_id, name) VALUES (510, 5, 'LA CRUZ')
SELECT * FROM DUAL;