INSERT ALL
   INTO canton(id, province_id, name, creation_user) VALUES (610, 6, 'CORREDORES', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (607, 6, 'GOLFITO', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (608, 6, 'COTO BRUS', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (605, 6, 'OSA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (603, 6, 'BUENOS AIRES', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (119, 1, 'PEREZ ZELEDON', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (606, 6, 'QUEPOS', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (704, 7, 'TALAMANCA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (609, 6, 'PARRITA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (105, 1, 'TARRAZU', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (117, 1, 'DOTA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (611, 6, 'GARABITO', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (120, 1, 'LEON CORTES CASTRO', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (104, 1, 'PURISCAL', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (106, 1, 'ASERRI', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (103, 1, 'DESAMPARADOS', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (112, 1, 'ACOSTA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (116, 1, 'TURRUBARES', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (308, 3, 'EL GUARCO', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (301, 3, 'CARTAGO', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (601, 6, 'PUNTARENAS', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (302, 3, 'PARAISO', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (304, 3, 'JIMENEZ', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (305, 3, 'TURRIALBA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (107, 1, 'MORA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (307, 3, 'OREAMUNO', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (110, 1, 'ALAJUELITA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (701, 7, 'LIMON', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (303, 3, 'LA UNION', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (118, 1, 'CURRIDABAT', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (209, 2, 'OROTINA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (101, 1, 'SAN JOSE', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (102, 1, 'ESCAZU', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (306, 3, 'ALVARADO', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (109, 1, 'SANTA ANA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (509, 5, 'NANDAYURE', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (115, 1, 'MONTES DE OCA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (108, 1, 'GOICOECHEA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (113, 1, 'TIBAS', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (204, 2, 'SAN MATEO', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (502, 5, 'NICOYA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (205, 2, 'ATENAS', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (201, 2, 'ALAJUELA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (114, 1, 'MORAVIA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (602, 6, 'ESPARZA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (111, 1, 'VAZQUEZ DE CORONADO', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (403, 4, 'SANTO DOMINGO', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (407, 4, 'BELEN', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (401, 4, 'HEREDIA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (409, 4, 'SAN PABLO', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (202, 2, 'SAN RAMON', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (511, 5, 'HOJANCHA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (408, 4, 'FLORES', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (405, 4, 'SAN RAFAEL', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (402, 4, 'BARVA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (406, 4, 'SAN ISIDRO', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (404, 4, 'SANTA BARBARA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (207, 2, 'PALMARES', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (208, 2, 'POAS', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (203, 2, 'GRECIA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (206, 2, 'NARANJO', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (604, 6, 'MONTES DE ORO', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (212, 2, 'VALVERDE VEGA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (703, 7, 'SIQUIRRES', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (705, 7, 'MATINA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (503, 5, 'SANTA CRUZ', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (211, 2, 'ZARCERO', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (706, 7, 'GUACIMO', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (507, 5, 'ABANGARES', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (702, 7, 'POCOCI', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (210, 2, 'SAN CARLOS', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (506, 5, 'CAÑAS', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (508, 5, 'TILARAN', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (410, 4, 'SARAPIQUI', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (505, 5, 'CARRILLO', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (216, 2, 'RIO CUARTO', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (504, 5, 'BAGACES', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (215, 2, 'GUATUSO', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (214, 2, 'LOS CHILES', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (501, 5, 'LIBERIA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (213, 2, 'UPALA', USER)
   INTO canton(id, province_id, name, creation_user) VALUES (510, 5, 'LA CRUZ', USER)
SELECT * FROM DUAL;