INSERT ALL
   INTO district(id, canton_id, name, creation_user) VALUES (10501, 105, 'SAN MARCOS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11702, 117, 'JARDÍN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (12005, 120, 'SANTA CRUZ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (12006, 120, 'SAN ANTONIO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (12002, 120, 'SAN ANDRÉS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10605, 106, 'LEGUA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10606, 106, 'MONTERREY', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10306, 103, 'FRAILES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11205, 112, 'SABANILLAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11204, 112, 'CANGREJAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10308, 103, 'SAN CRISTOBAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30804, 308, 'PATIO DE AGUA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10603, 106, 'VUELTA DE JORCO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10604, 106, 'SAN GABRIEL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30107, 301, 'CORRALILLO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11202, 112, 'GUAITIL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30203, 302, 'OROSI', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11201, 112, 'SAN IGNACIO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10309, 103, 'ROSARIO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30803, 308, 'TOBOSI', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10602, 106, 'TARBACA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30801, 308, 'EL TEJAR', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30105, 301, 'AGUACALIENTE O SAN FRANCISCO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30403, 304, 'PEJIBAYE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30109, 301, 'DULCE NOMBRE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11203, 112, 'PALMICHAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30205, 302, 'LLANOS DE SANTA LUCÍA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30101, 301, 'ORIENTAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10607, 106, 'SALITRILLOS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30102, 301, 'OCCIDENTAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10601, 106, 'ASERRÍ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30402, 304, 'TUCURRIQUE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30204, 302, 'CACHÍ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30201, 302, 'PARAÍSO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10702, 107, 'GUAYABO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10313, 103, 'LOS GUIDO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30106, 301, 'GUADALUPE O ARENILLA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30111, 301, 'QUEBRADILLA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10307, 103, 'PATARRÁ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10302, 103, 'SAN MIGUEL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10703, 107, 'TABARCIA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10303, 103, 'SAN JUAN DE DIOS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30701, 307, 'SAN RAFAEL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10304, 103, 'SAN RAFAEL ARRIBA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30103, 301, 'CARMEN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11003, 110, 'SAN ANTONIO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30308, 303, 'RÍO AZUL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10310, 103, 'DAMAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10312, 103, 'GRAVILIAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11002, 110, 'SAN JOSECITO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11004, 110, 'CONCEPCIÓN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10305, 103, 'SAN ANTONIO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10311, 103, 'SAN RAFAEL ABAJO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30202, 302, 'SANTIAGO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30302, 303, 'SAN DIEGO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10301, 103, 'DESAMPARADOS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11804, 118, 'TIRRASES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11001, 110, 'ALAJUELITA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30704, 307, 'CIPRESES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30301, 303, 'TRES RÍOS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30702, 307, 'COT', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10106, 101, 'SAN FRANCISCO DE DOS RÍOS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10202, 102, 'SAN ANTONIO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10111, 101, 'SAN SEBASTIÁN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30602, 306, 'CERVANTES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30304, 303, 'SAN RAFAEL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30303, 303, 'SAN JUAN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10902, 109, 'SALITRAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10201, 102, 'ESCAZÚ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10105, 101, 'ZAPOTE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30104, 301, 'SAN NICOLÁS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11801, 118, 'CURRIDABAT', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11803, 118, 'SÁNCHEZ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11005, 110, 'SAN FELIPE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10110, 101, 'HATILLO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10104, 101, 'CATEDRAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10701, 107, 'COLÓN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10103, 101, 'HOSPITAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30305, 303, 'CONCEPCIÓN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11802, 118, 'GRANADILLA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10101, 101, 'EL CARMEN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30307, 303, 'SAN RAMÓN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10901, 109, 'SANTA ANA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10905, 109, 'PIEDADES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11501, 115, 'SAN PEDRO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10802, 108, 'SAN FRANCISCO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10108, 101, 'MATA REDONDA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10102, 101, 'MERCED', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10904, 109, 'URUCA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30401, 304, 'JUAN VIÑAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10906, 109, 'BRASIL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30306, 303, 'DULCE NOMBRE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11503, 115, 'MERCEDES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11302, 113, 'CINCO ESQUINAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11502, 115, 'SABANILLA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10803, 108, 'CALLE BLANCOS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11504, 115, 'SAN RAFAEL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10801, 108, 'GUADALUPE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30509, 305, 'SANTA ROSA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11303, 113, 'ANSELMO LLORENTE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11304, 113, 'LEÓN XIII', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10109, 101, 'PAVAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10804, 108, 'MATA DE PLÁTANO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11305, 113, 'COLIMA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10807, 108, 'PURRAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10805, 108, 'IPÍS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30110, 301, 'LLANO GRANDE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30108, 301, 'TIERRA BLANCA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10107, 101, 'URUCA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30703, 307, 'POTRERO CERRADO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10203, 102, 'SAN RAFAEL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11301, 113, 'SAN JUAN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10903, 109, 'POZOS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10806, 108, 'RANCHO REDONDO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11401, 114, 'SAN VICENTE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30601, 306, 'PACAYAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11101, 111, 'SAN ISIDRO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40301, 403, 'SANTO DOMINGO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11104, 111, 'PATALILLO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40306, 403, 'SANTA ROSA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40701, 407, 'SAN ANTONIO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40305, 403, 'SANTO TOMÁS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40104, 401, 'ULLOA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20108, 201, 'SAN RAFAEL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11102, 111, 'SAN RAFAEL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40703, 407, 'LA ASUNCIÓN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11403, 114, 'LA TRINIDAD', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40902, 409, 'RINCÓN DE SABANILLA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40302, 403, 'SAN VICENTE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40303, 403, 'SAN MIGUEL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20105, 201, 'GUÁCIMA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40103, 401, 'SAN FRANCISCO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40803, 408, 'LLORENTE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40702, 407, 'LA RIBERA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40307, 403, 'TURES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40101, 401, 'HEREDIA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20104, 201, 'SAN ANTONIO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40801, 408, 'SAN JOAQUÍN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40901, 409, 'SAN PABLO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40503, 405, 'SANTIAGO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20109, 201, 'RÍO SEGUNDO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40304, 403, 'PARACITO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40308, 403, 'PARÁ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40102, 401, 'MERCEDES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30603, 306, 'CAPELLADES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40502, 405, 'SAN JOSECITO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40604, 406, 'SAN FRANCISCO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40601, 406, 'SAN ISIDRO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20102, 201, 'SAN JOSÉ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40403, 404, 'SAN JUAN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20101, 201, 'ALAJUELA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20112, 201, 'TAMBOR', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40602, 406, 'SAN JOSÉ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20110, 201, 'DESAMPARADOS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11402, 114, 'SAN JERÓNIMO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40505, 405, 'CONCEPCIÓN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30504, 305, 'SANTA CRUZ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11105, 111, 'CASCAJAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30705, 307, 'SANTA ROSA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11103, 111, 'DULCE NOMBRE DE JESÚS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10707, 107, 'QUITIRRISI', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30802, 308, 'SAN ISIDRO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (61002, 610, 'LA CUESTA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (61004, 610, 'LAUREL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (61003, 610, 'CANOAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60702, 607, 'PUERTO JIMÉNEZ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (61001, 610, 'CORREDOR', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60701, 607, 'GOLFITO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60803, 608, 'AGUABUENA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60506, 605, 'BAHÍA DRAKE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60703, 607, 'GUAYCARÁ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60505, 605, 'PIEDRAS BLANCAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60801, 608, 'SAN VITO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60804, 608, 'LIMONCITO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60503, 605, 'SIERPE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60802, 608, 'SABALITO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60307, 603, 'CHÁNGUENA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60502, 605, 'PALMAR', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60306, 603, 'COLINAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60304, 603, 'BORUCA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60806, 608, 'GUTIÉRREZ BRAUN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60805, 608, 'PITTIER', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60501, 605, 'PUERTO CORTÉS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60305, 603, 'PILAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60308, 603, 'BIOLLEY', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11907, 119, 'PEJIBAYE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11912, 119, 'LA  AMISTAD', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11906, 119, 'PLATANARES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60309, 603, 'BRUNKA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60302, 603, 'VOLCÁN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60303, 603, 'POTRERO GRANDE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11903, 119, 'DANIEL FLORES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11909, 119, 'BARÚ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11908, 119, 'CAJÓN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11905, 119, 'SAN PEDRO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11902, 119, 'EL GENERAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60602, 606, 'SAVEGRE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11901, 119, 'SAN ISIDRO DE EL GENERAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11910, 119, 'RÍO NUEVO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60603, 606, 'NARANJITO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11904, 119, 'RIVAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11911, 119, 'PÁRAMO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70402, 704, 'SIXAOLA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60901, 609, 'PARRITA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10502, 105, 'SAN LORENZO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10503, 105, 'SAN CARLOS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70401, 704, 'BRATSI', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70404, 704, 'TELIRE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11703, 117, 'COPEY', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11701, 117, 'SANTA MARÍA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (61101, 611, 'JACÓ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (12004, 120, 'SAN ISIDRO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (12001, 120, 'SAN PABLO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (12003, 120, 'LLANO BONITO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10409, 104, 'CHIRES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70403, 704, 'CAHUITA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11605, 116, 'CARARA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60111, 601, 'CÓBANO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10406, 104, 'CANDELARITA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10402, 104, 'MERCEDES SUR', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10405, 104, 'SAN RAFAEL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30508, 305, 'TAYUTIC', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11604, 116, 'SAN LUIS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (61102, 611, 'TÁRCOLES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10403, 104, 'BARBACOAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10401, 104, 'SANTIAGO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10706, 107, 'JARIS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10408, 104, 'SAN ANTONIO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11603, 116, 'SAN JUAN DE MATA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70102, 701, 'VALLE DE LA ESTRELLA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30507, 305, 'TUIS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10407, 104, 'DESAMPARADITOS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11602, 116, 'SAN PEDRO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20904, 209, 'COYOLAR', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10404, 104, 'GRIFO ALTO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10704, 107, 'PIEDRAS NEGRAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (11601, 116, 'SAN PABLO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50906, 509, 'BEJUCO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30502, 305, 'LA SUIZA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20901, 209, 'OROTINA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30501, 305, 'TURRIALBA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20902, 209, 'EL MASTATE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20905, 209, 'LA CEIBA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (10705, 107, 'PICAGRES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20903, 209, 'HACIENDA VIEJA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30511, 305, 'LA ISABEL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70104, 701, 'MATAMA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30506, 305, 'PAVONES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20404, 204, 'LABRADOR', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50205, 502, 'SÁMARA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50905, 509, 'PORVENIR', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20508, 205, 'ESCOBAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20111, 201, 'TURRÚCARES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60206, 602, 'CALDERA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30510, 305, 'TRES EQUIS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60101, 601, 'PUNTARENAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30503, 305, 'PERALTA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20403, 204, 'JESÚS MARÍA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20505, 205, 'CONCEPCIÓN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20502, 205, 'JESÚS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20202, 202, 'SANTIAGO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60202, 602, 'SAN JUAN GRANDE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60115, 601, 'EL ROBLE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60112, 601, 'CHACARITA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20501, 205, 'ATENAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20402, 204, 'DESMONTE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20503, 205, 'MERCEDES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (51103, 511, 'PUERTO CARRILLO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20504, 205, 'SAN ISIDRO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20401, 204, 'SAN MATEO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20113, 201, 'GARITA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60201, 602, 'ESPÍRITU SANTO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60104, 601, 'LEPANTO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50903, 509, 'ZAPOTAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (51102, 511, 'MONTE ROMO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40802, 408, 'BARRANTES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40204, 402, 'SAN ROQUE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40501, 405, 'SAN RAFAEL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40201, 402, 'BARVA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50901, 509, 'CARMONA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60204, 602, 'SAN RAFAEL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20704, 207, 'SANTIAGO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20507, 205, 'SANTA EULALIA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20506, 205, 'SAN JOSÉ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20705, 207, 'CANDELARIA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40205, 402, 'SANTA LUCÍA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30505, 305, 'SANTA TERESITA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60108, 601, 'BARRANCA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40402, 404, 'SAN PEDRO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40401, 404, 'SANTA BÁRBARA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60203, 602, 'MACACONA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20702, 207, 'ZARAGOZA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20804, 208, 'CARRILLOS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50206, 502, 'NOSARA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20701, 207, 'PALMARES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20307, 203, 'PUENTE DE PIEDRA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40603, 406, 'CONCEPCIÓN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70103, 701, 'RÍO BLANCO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50207, 502, 'BELÉN DE NOSARITA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40202, 402, 'SAN PEDRO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70101, 701, 'LIMÓN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20707, 207, 'LA GRANJA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (51104, 511, 'HUACAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20607, 206, 'EL ROSARIO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20706, 207, 'ESQUIPULAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50904, 509, 'SAN PABLO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50902, 509, 'SANTA RITA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20301, 203, 'GRECIA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40203, 402, 'SAN PABLO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40404, 404, 'JESÚS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20206, 202, 'SAN RAFAEL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20703, 207, 'BUENOS AIRES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20602, 206, 'SAN MIGUEL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60403, 604, 'SAN ISIDRO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20201, 202, 'SAN RAMÓN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40406, 404, 'PURABÁ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21202, 212, 'SARCHÍ SUR', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (51101, 511, 'HOJANCHA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60102, 601, 'PITAHAYA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20207, 202, 'SAN ISIDRO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70303, 703, 'FLORIDA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20209, 202, 'ALFARO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20608, 206, 'PALMITOS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20801, 208, 'SAN PEDRO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20203, 202, 'SAN JUAN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40504, 405, 'ÁNGELES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20103, 201, 'CARRIZAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70503, 705, 'CARRANDI', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60205, 602, 'SAN JERÓNIMO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60113, 601, 'CHIRA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20606, 206, 'SAN JUAN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20601, 206, 'NARANJO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20803, 208, 'SAN RAFAEL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40206, 402, 'SAN JOSÉ DE LA MONTAÑA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20305, 203, 'TACARES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50306, 503, 'CUAJINIQUIL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20211, 202, 'CONCEPCIÓN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21205, 212, 'RODRÍGUEZ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20205, 202, 'PIEDADES SUR', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40405, 404, 'SANTO DOMINGO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20106, 201, 'SAN ISIDRO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70306, 703, 'LA ALEGRÍA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20605, 206, 'SAN JERÓNIMO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70501, 705, 'MATINA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20603, 206, 'SAN JOSÉ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60401, 604, 'MIRAMAR', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60103, 601, 'CHOMES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20304, 203, 'SAN ROQUE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20302, 203, 'SAN ISIDRO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21201, 212, 'SARCHÍ NORTE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20204, 202, 'PIEDADES NORTE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20308, 203, 'BOLIVAR', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21204, 212, 'SAN PEDRO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20210, 202, 'VOLIO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20604, 206, 'CIRRÍ SUR', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20107, 201, 'SABANILLA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20802, 208, 'SAN JUAN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20805, 208, 'SABANA REDONDA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20212, 202, 'ZAPOTAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60106, 601, 'MANZANILLO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21101, 211, 'ZARCERO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50202, 502, 'MANSIÓN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21104, 211, 'GUADALUPE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70304, 703, 'GERMANIA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (30512, 305, 'CHIRRIPÓ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21103, 211, 'TAPESCO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70302, 703, 'PACUARITO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70602, 706, 'MERCEDES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21105, 211, 'PALMIRA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70603, 706, 'POCORA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21102, 211, 'LAGUNA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50204, 502, 'QUEBRADA HONDA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60114, 601, 'ACAPULCO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21107, 211, 'BRISAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21106, 211, 'ZAPOTE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60116, 601, 'ARANCIBIA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21203, 212, 'TORO AMARILLO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60107, 601, 'GUACIMAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50703, 507, 'SAN JUAN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50704, 507, 'COLORADO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60402, 604, 'LA UNIÓN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70305, 703, 'EL CAIRO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (40105, 401, 'VARABLANCA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70202, 702, 'JIMÉNEZ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70601, 706, 'GUÁCIMO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70604, 706, 'RÍO JIMÉNEZ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70207, 702, 'LA COLONIA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21003, 210, 'BUENAVISTA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50303, 503, 'VEINTISIETE DE ABRIL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70301, 703, 'SIQUIRRES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70201, 702, 'GUÁPILES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60109, 601, 'MONTE VERDE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50605, 506, 'POROZAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50307, 503, 'DIRIÁ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50203, 502, 'SAN ANTONIO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70605, 706, 'DUACARÍ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50701, 507, 'LAS JUNTAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50201, 502, 'NICOYA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50309, 503, 'TAMARINDO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50302, 503, 'BOLSÓN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20214, 202, 'SAN LORENZO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50702, 507, 'SIERRA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21008, 210, 'LA TIGRA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50603, 506, 'SAN MIGUEL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20114, 201, 'SARAPIQUÍ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21005, 210, 'VENECIA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50604, 506, 'BEBEDERO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21001, 210, 'QUESADA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50305, 503, 'CARTAGENA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50802, 508, 'QUEBRADA GRANDE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50308, 503, 'CABO VELAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50805, 508, 'LÍBANO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20213, 202, 'PEÑAS BLANCAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (41003, 410, 'LAS HORQUETAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70204, 702, 'ROXANA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50501, 505, 'FILADELFIA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21002, 210, 'FLORENCIA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21009, 210, 'LA PALMERA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50504, 505, 'BELÃ¯Â¿Â½N', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50304, 503, 'TEMPATE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50803, 508, 'TRONADORA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21007, 210, 'LA FORTUNA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50601, 506, 'CAÑAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70205, 702, 'CARIARI', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50801, 508, 'TILARAN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50804, 508, 'SANTA ROSA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21601, 216, 'RÍO CUARTO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21004, 210, 'AGUAS ZARCAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50807, 508, 'ARENAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70203, 702, 'RITA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50502, 505, 'PALMIRA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50503, 505, 'SARDINAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21010, 210, 'VENADO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50401, 504, 'BAGACES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50806, 508, 'TIERRAS MORENAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21012, 210, 'MONTERREY', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (41002, 410, 'LA VIRGEN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21503, 215, 'COTE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50602, 506, 'PALMIRA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (41001, 410, 'PUERTO VIEJO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50404, 504, 'RÍO NARANJO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50402, 504, 'LA FORTUNA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (41004, 410, 'LLANURAS DEL GASPAR', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21501, 215, 'SAN RAFAEL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50403, 504, 'MOGOTE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21006, 210, 'PITAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (41005, 410, 'CUREÑA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21404, 214, 'SAN JORGE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50101, 501, 'LIBERIA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21304, 213, 'BIJAGUA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21504, 215, 'KATIRA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50105, 501, 'CURUBANDÉ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21502, 215, 'BUENAVISTA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50102, 501, 'CAÑAS DULCES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50104, 501, 'NACASCOLO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21308, 213, 'CANALETE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21011, 210, 'CUTRIS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21403, 214, 'EL AMPARO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70206, 702, 'COLORADO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21301, 213, 'UPALA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50103, 501, 'MAYORGA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21307, 213, 'YOLILLAL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21302, 213, 'AGUAS CLARAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (51004, 510, 'SANTA ELENA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21013, 210, 'POCOSOL', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21305, 213, 'DELICIAS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21306, 213, 'DOS RÍOS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21402, 214, 'CAÑO NEGRO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21303, 213, 'SAN JOSÉ O PIZOTE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (21401, 214, 'LOS CHILES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (51002, 510, 'SANTA CECILIA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (51003, 510, 'LA GARITA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (51001, 510, 'LA CRUZ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60504, 605, 'BAHÍA BALLENA', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60704, 607, 'PAVÓN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (70502, 705, 'BATÁN', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20303, 203, 'SAN JOSE', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60601, 606, 'QUEPOS', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60301, 603, 'BUENOS AIRES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (50301, 503, 'SANTA CRUZ', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60110, 601, 'ISLA DEL COCO', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (20208, 202, 'ÁNGELES', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (51105, 511, 'MATAMBU', USER)
   INTO district(id, canton_id, name, creation_user) VALUES (60105, 601, 'PAQUERA', USER)
SELECT * FROM DUAL;