INSERT ALL
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (9, 'CIRCUITO JUDICIAL DE CARTAGO', 301, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (27, 'CIRCUITO JUDICIAL DE CARTAGO (ALVARADO)', 306, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (30, 'CIRCUITO JUDICIAL DE CARTAGO (JIMÉNEZ)', 304, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (24, 'CIRCUITO JUDICIAL DE CARTAGO (LA UNIÓN)', 303, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (29, 'CIRCUITO JUDICIAL DE CARTAGO (PARAÍSO)', 302, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (28, 'CIRCUITO JUDICIAL DE CARTAGO (TARRAZÚ, DOTA Y LEÓN CORTÉS)', 105,USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (5, 'CIRCUITO JUDICIAL DE HEREDIA', 401, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (74, 'CIRCUITO JUDICIAL DE HEREDIA (SAN ISIDRO)', 406, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (44, 'CIRCUITO JUDICIAL DE HEREDIA (SAN JOAQUíN)', 408, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (75, 'CIRCUITO JUDICIAL DE HEREDIA (SAN RAFAEL)', 405, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (73, 'CIRCUITO JUDICIAL DE HEREDIA (SANTO DOMINGO)', 403, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (22, 'CIRCUITO JUDICIAL DE HEREDIA (SARAPIQuí)', 410, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (6, 'CIRCUITO JUDICIAL DE PUNTARENAS', 601, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (59, 'CIRCUITO JUDICIAL DE PUNTARENAS (CóBANO)', 601, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (69, 'CIRCUITO JUDICIAL DE PUNTARENAS (ESPARZA)', 602, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (42, 'CIRCUITO JUDICIAL DE PUNTARENAS (GARABITO)', 611, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (70, 'CIRCUITO JUDICIAL DE PUNTARENAS (MONTES DE ORO - MIRAMAR)', 504,USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (60, 'CIRCUITO JUDICIAL DE PUNTARENAS (MONTEVERDE)', 601, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (71, 'CIRCUITO JUDICIAL DE PUNTARENAS (PARRITA)', 609, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (43, 'CIRCUITO JUDICIAL DE PUNTARENAS (QUEPOS)', 606, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (18, 'CIRCUITO JUDICIAL DE TURRIALBA', 305, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (47, 'I CIRCUITO DE LA ZONA ATLÁNTICA (BATÁN-MATINA)', 705, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (46, 'I CIRCUITO DE LA ZONA ATLÁNTICA (BRIBRÍ)', 704, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (10, 'I CIRCUITO DE LA ZONA ATLANTICA (LIMON)', 701, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (3, 'I CIRCUITO JUDICIAL DE ALAJUELA', 201, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (14, 'I CIRCUITO JUDICIAL DE ALAJUELA (ATENAS)', 205, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (32, 'I CIRCUITO JUDICIAL DE ALAJUELA (OROTINA)', 209, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (33, 'I CIRCUITO JUDICIAL DE ALAJUELA (PÓAS)', 208, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (31, 'I CIRCUITO JUDICIAL DE ALAJUELA (SAN MATEO)', 204, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (54, 'I CIRCUITO JUDICIAL DE GUANACASTE (ABANGARES)', 507, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (51, 'I CIRCUITO JUDICIAL DE GUANACASTE (BAGACES)', 504, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (50, 'I CIRCUITO JUDICIAL DE GUANACASTE (CAÑAS)', 506, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (52, 'I CIRCUITO JUDICIAL DE GUANACASTE (LA CRUZ)', 510, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (7, 'I CIRCUITO JUDICIAL DE GUANACASTE (LIBERIA)', 501, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (53, 'I CIRCUITO JUDICIAL DE GUANACASTE (TILARAN)', 508, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (49, 'I CIRCUITO JUDICIAL DE LA ZONA SUR (BUENOS AIRES)', 603, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (8, 'I CIRCUITO JUDICIAL DE LA ZONA SUR (PEREZ ZELEDON)', 119, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (1, 'I CIRCUITO JUDICIAL DE SAN JOSE', 101, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (45, 'I CIRCUITO JUDICIAL DE SAN JOSÉ (PURISCAL)', 104, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (61, 'I CIRCUITO JUDICIAL DE SAN JOSÉ (TURRUBARES)', 116, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (58, 'II CIRCUITO DE LA ZONA ATLÁNTICA (GUÁCIMO)', 706, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (11, 'II CIRCUITO DE LA ZONA ATLÁNTICA (POCOCI)', 702, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (48, 'II CIRCUITO DE LA ZONA ATLÁNTICA (SIQUIRRES)', 703, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (40, 'II CIRCUITO JUDICIAL DE ALAJUELA (GUATUSO)', 215, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (41, 'II CIRCUITO JUDICIAL DE ALAJUELA (LA FORTUNA)', 210, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (39, 'II CIRCUITO JUDICIAL DE ALAJUELA (LOS CHILES)', 214, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (4, 'II CIRCUITO JUDICIAL DE ALAJUELA (SAN CARLOS)', 210, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (38, 'II CIRCUITO JUDICIAL DE ALAJUELA (UPALA)', 213, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (56, 'II CIRCUITO JUDICIAL DE GUANACASTE (CARILLO)', 505, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (72, 'II CIRCUITO JUDICIAL DE GUANACASTE (HOJANCHA)', 511, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (55, 'II CIRCUITO JUDICIAL DE GUANACASTE (JICARAL)', 601, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (57, 'II CIRCUITO JUDICIAL DE GUANACASTE (NANDAYURE)', 509, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (15, 'II CIRCUITO JUDICIAL DE GUANACASTE (NICOYA)', 502, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (13, 'II CIRCUITO JUDICIAL DE GUANACASTE (SANTA CRUZ)', 503, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (16, 'II CIRCUITO JUDICIAL DE LA ZONA SUR (CORREDORES)', 610, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (26, 'II CIRCUITO JUDICIAL DE LA ZONA SUR (COTO BRUS)', 608, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (19, 'II CIRCUITO JUDICIAL DE LA ZONA SUR (GOLFITO)', 607, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (21, 'II CIRCUITO JUDICIAL DE LA ZONA SUR (GOLFITO) (PUERTO JIMÉNEZ)', 607, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (25, 'II CIRCUITO JUDICIAL DE LA ZONA SUR (OSA)', 605, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (2, 'II CIRCUITO JUDICIAL DE SAN JOSE (GOICOECHEA)', 108, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (20, 'III CIRCUITO JUDICIAL DE ALAJUELA (GRECIA)', 203, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (36, 'III CIRCUITO JUDICIAL DE ALAJUELA (NARANJO)', 206, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (35, 'III CIRCUITO JUDICIAL DE ALAJUELA (PALMARES)', 207, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (12, 'III CIRCUITO JUDICIAL DE ALAJUELA (SAN RAMON)', 202, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (34, 'III CIRCUITO JUDICIAL DE ALAJUELA (SARCHÁ)', 212, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (37, 'III CIRCUITO JUDICIAL DE ALAJUELA (ZARCERO)', 211, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (65, 'III CIRCUITO JUDICIAL DE SAN JOSÉ (ACOSTA)', 112, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (64, 'III CIRCUITO JUDICIAL DE SAN JOSÉ (ASERRÁ)', 106, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (17, 'III CIRCUITO JUDICIAL DE SAN JOSÉ (DESAMPARADOS)', 103, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (67, 'III CIRCUITO JUDICIAL DE SAN JOSÉ (ESCAZÚ)', 102, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (62, 'III CIRCUITO JUDICIAL DE SAN JOSÉ (HATILLO, SAN SEBASTIÁN Y ALAJUELITA)', 101, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (63, 'III CIRCUITO JUDICIAL DE SAN JOSÉ (MORA)', 107, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (66, 'III CIRCUITO JUDICIAL DE SAN JOSÉ (PAVAS)', 101, USER)
   INTO judicial_circuit(id, description_, canton_id, creation_user) VALUES (68, 'III CIRCUITO JUDICIAL DE SAN JOSÉ (SANTA ANA)', 109, USER)
SELECT * FROM DUAL;