INSERT ALL
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 0004, 'SALA PRIMERA', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 0006, 'SALA TERCERA', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 0007, 'SALA CONSTITUCIONAL', 'CO', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 0009, 'TRIBUNAL PRIMERO DE APELACION CIVIL DE SAN JOSÉ', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 0010, 'TRIBUNAL SEGUNDO DE APELACION CIVIL DE SAN JOSÉ', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 0016, 'TRIBUNAL PENAL DEL I CIRCUITO JUDICIAL DE SAN JOSÉ', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (2, 0028, 'TRIBUNAL DE APELACION DE TRABAJO II CIRCUITO JUDICIAL SAN JOSÉ', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (2, 0029, 'TRIBUNAL AGRARIO DEL II CIRCUITO JUDICIAL DE SAN JOSÉ', 'AG', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (8, 0030, 'TRIBUNAL PENAL DEL I CIRCUITO JUDICIAL DE LA ZONA SUR (PÉREZ ZELEDÓN)', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (2, 0161, 'TRIBUNAL CONTENCIOSO ADMINISTRATIVO DEL II CIRCUITO JUDICIAL DE SAN JOSÉ', 'CA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (2, 0163, 'JUZGADO CONTENCIOSO ADMINISTRATIVO Y CIVIL DE HACIENDA DEL II CIRCUITO JUDICIAL DE SAN JOSÉ', 'CA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (2, 0166, 'JUZGADO DE TRABAJO DEL II CIRCUITO JUDICIAL DE SAN JOSÉ', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (2, 0171, 'JUZGADO CONTRAVENCIONAL DEL II CIRCUITO JUDICIAL DE SAN JOSÉ', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 0173, 'JUZGADO DE TRABAJO DEL I CIRCUITO JUDICIAL DE SAN JOSÉ - SECCIÓN SEGUNDA', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (2, 0174, 'JUZGADO DE TRÁNSITO DEL II CIRCUITO JUDICIAL DE SAN JOSÉ', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 0180, 'JUZGADO PRIMERO CIVIL DE SAN JOSÉ', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 0181, 'JUZGADO SEGUNDO CIVIL DE SAN JOSÉ', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 0182, 'JUZGADO TERCERO CIVIL DE SAN JOSÉ', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (8, 0188, 'JUZGADO CIVIL DEL I CIRCUITO JUDICIAL DE LA ZONA SUR (PÉREZ ZELEDÓN)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (45, 0197, 'JUZGADO CIVIL - TRABAJO Y FAMILIA DE PURISCAL (MATERIA CIVIL)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (62, 0216, 'JUZGADO CIVIL - TRABAJO Y FAMILIA DE HATILLO - SAN SEBASTIÁN Y ALAJUELITA (MATERIA CIVIL)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (17, 0217, 'JUZGADO CIVIL Y TRABAJO DEL III CIRCUITO JUDICIAL DE SAN JOSÉ (DESAMPARADOS) (MATERIA CIVIL)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 0220, 'JUZGADO PRIMERO CIVIL DE MENOR CUANTÍA DE SAN JOSÉ', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 0221, 'JUZGADO SEGUNDO CIVIL DE MENOR CUANTÍA DE SAN JOSÉ', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (3, 0285, 'TRIBUNAL DEL I CIRCUITO JUDICIAL DE ALAJUELA', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (4, 0288, 'TRIBUNAL PENAL DEL II CIRCUITO JUDICIAL DE ALAJUELA', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (20, 0295, 'JUZGADO CIVIL DE GRECIA', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (12, 0296, 'JUZGADO CIVIL MAYOR CUANTÍA DEL III CIRCUITO JUDICIAL DE ALAJUELA (SAN RAMÓN)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (4, 0297, 'JUZGADO CIVIL DEL II CIRCUITO JUDICIAL DE ALAJUELA (MATERIA CIVIL)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (4, 0298, 'JUZGADO AGRARIO DEL II CIRCUITO JUDICIAL DE ALAJUELA', 'AG', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (12, 0316, 'JUZGADO CONTRAVENCIONAL DEL III CIRCUITO JUDICIAL DE ALAJUELA (SAN RAMÓN)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (9, 0335, 'TRIBUNAL PENAL DE CARTAGO', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (18, 0341, 'JUZGADO CIVIL Y TRABAJO DE TURRIALBA', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (5, 0361, 'TRIBUNAL DE HEREDIA', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (7, 0384, 'TRIBUNAL PENAL DE LIBERIA', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (7, 0386, 'JUZGADO CIVIL DE MAYOR CUANTÍA DE LIBERIA', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (7, 0387, 'JUZGADO AGRARIO DE LIBERIA', 'AG', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (13, 0388, 'JUZGADO CIVIL DE SANTA CRUZ', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (15, 0390, 'JUZGADO CIVIL DE NICOYA', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (13, 0391, 'JUZGADO AGRARIO DE SANTA CRUZ', 'AG', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (13, 0400, 'JUZGADO CONTRAVENCIONAL DE SANTA CRUZ', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (16, 0419, 'JUZGADO AGRARIO DEL II CIRCUITO JUDICIAL DE LA ZONA SUR (CORREDORES)', 'AG', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (19, 0422, 'JUZGADO CIVIL DE GOLFITO', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (25, 0423, 'JUZGADO CIVIL - II CIRCUITO JUDICIAL ZONA SUR (OSA)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (43, 0425, 'JUZGADO CIVIL Y DE TRABAJO DE QUEPOS\~ (MATERIA CIVIL)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (10, 0459, 'TRIBUNAL PENAL DE I CIRC. JUD. DE LA ZONA ATLÁNTICA', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (10, 0465, 'JUZGADO AGRARIO DEL I CIRCUITO JUDICIAL DE LA ZONA ATLÁNTICA', 'AG', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 0489, 'JUZGADO DE TRÁNSITO DEL I CIRCUITO JUDICIAL DE SAN JOSÉ', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (17, 0491, 'JUZGADO DE TRÁNSITO DEL III CIRCUITO JUDICIAL DE SAN JOSÉ (DESAMPARADOS)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (62, 0492, 'JUZGADO DE TRÁNSITO DE HATILLO', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (3, 0494, 'JUZGADO DE TRÁNSITO DEL I CIRCUITO JUDICIAL DE ALAJUELA', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (12, 0495, 'JUZGADO DE TRÁNSITO DEL III CIRCUITO JUDICIAL DE ALAJUELA (SAN RAMÓN)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (9, 0496, 'JUZGADO DE TRÁNSITO DE CARTAGO', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (5, 0497, 'JUZGADO DE TRÁNSITO DE HEREDIA', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (10, 0498, 'JUZGADO DE TRÁNSITO DEL I CIRCUITO JUDICIAL DE LA ZONA ATLÁNTICA', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (11, 0499, 'JUZGADO DE TRÁNSITO DEL II CIRCUITO JUDICIAL DE LA ZONA ATLÁNTICA', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (66, 0500, 'JUZGADO DE TRÁNSITO DE PAVAS', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (5, 0504, 'JUZGADO CIVIL DE HEREDIA', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (5, 0505, 'JUZGADO DE TRABAJO DE HEREDIA', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (11, 0507, 'JUZGADO AGRARIO DEL II CIRCUITO JUDICIAL DE LA ZONA ATLÁNTICA', 'AG', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (19, 0536, 'TRIBUNAL II CIRCUITO JUDICIAL ZONA SUR - SEDE GOLFITO', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (25, 0537, 'TRIBUNAL DEL II CIRCUITO JUDICIAL DE LA ZONA SUR - SEDE OSA', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (19, 0539, 'JUZGADO PENAL DE GOLFITO', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (20, 0547, 'TRIBUNAL PENAL DE GRECIA', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (12, 0548, 'TRIBUNAL DE JUICIO DEL III CIRCUITO JUDICIAL DE ALAJUELA (SAN RAMÓN)', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (18, 0563, 'TRIBUNAL DE CARTAGO - SEDE TURRIALBA', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (15, 0577, 'TRIBUNAL DEL II CIRCUITO JUDICIAL DE GUANACASTE', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (11, 0601, 'TRIBUNAL DEL II CIRCUITO JUDICIAL DE LA ZONA ATLÁNTICA', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (6, 0607, 'JUZGADO DE TRÁNSITO DE PUNTARENAS', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 0626, 'JUZGADO CONTRAVENCIONAL DEL I CIRCUITO JUDICIAL DE SAN JOSÉ', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (3, 0638, 'JUZGADO CIVIL DEL I CIRCUITO JUDICIAL DE ALAJUELA', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (3, 0639, 'JUZGADO DE TRABAJO DEL I CIRCUITO JUDICIAL DE ALAJUELA', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (9, 0640, 'JUZGADO CIVIL DE CARTAGO', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (9, 0641, 'JUZGADO DE TRABAJO DE CARTAGO', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (6, 0642, 'JUZGADO CIVIL Y AGRARIO DE PUNTARENAS (MATERIA CIVIL)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (6, 0643, 'JUZGADO DE TRABAJO DE PUNTARENAS', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (10, 0678, 'JUZGADO CIVIL DEL I CIRCUITO JUDICIAL DE LA ZONA ATLÁNTICA', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (10, 0679, 'JUZGADO DE TRABAJO DEL I CIRCUITO JUDICIAL DE LA ZONA ATLÁNTICA ', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (11, 0680, 'JUZGADO CONTRAVENCIONAL DE POCOCI', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (2, 0689, 'JUZGADO AGRARIO DEL II CIRCUITO JUDICIAL DE SAN JOSÉ', 'AG', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (12, 0694, 'JUZGADO MAYOR CUANTÍA DEL III CIRCUITO JUDICIAL DE ALAJUELA (SAN RAMÓN)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (9, 0697, 'TRIBUNAL DE APELACIÓN CIVIL Y TRABAJO CARTAGO (SEDE CARTAGO) (MATERIA CIVIL)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (9, 0698, 'TRIBUNAL DE TRABAJO DE CARTAGO', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (9, 0699, 'JUZGADO AGRARIO DE CARTAGO', 'AG', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (4, 0742, 'JUZGADO DE TRÁNSITO DEL II CIRCUITO JUDICIAL DE ALAJUELA', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (15, 0768, 'JUZGADO DE TRÁNSITO DE NICOYA', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (9, 0771, 'JUZGADO CONTRAVENCIONAL DE CARTAGO', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (13, 0775, 'JUZGADO DE TRABAJO DE SANTA CRUZ', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (13, 0783, 'JUZGADO DE TRÁNSITO DE SANTA CRUZ', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (8, 0804, 'JUZGADO DE TRÁNSITO DEL I CIRCUITO JUDICIAL DE LA ZONA SUR (PÉREZ ZELEDÓN)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (17, 0805, 'JUZGADO CONTRAVENCIONAL DEL III CIRCUITO JUDICIAL DE SAN JOSÉ (DESAMPARADOS)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (3, 0806, 'JUZGADO CONTRAVENCIONAL DEL I CIRCUITO JUDICIAL DE ALAJUELA', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (5, 0807, 'JUZGADO CONTRAVENCIONAL DE HEREDIA', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (5, 0808, 'TRIBUNAL DE APELACIÓN CIVIL Y TRABAJO HEREDIA (SEDE HEREDIA) (MATERIA CIVIL)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (5, 0809, 'TRIBUNAL DE TRABAJO DE HEREDIA', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (3, 0813, 'TRIBUNAL DE APELACIÓN CIVIL Y TRABAJO ALAJUELA (SEDE ALAJUELA) (MATERIA CIVIL)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (3, 0814, 'TRIBUNAL DE TRABAJO DEL I CIRCUITO JUDICIAL DE ALAJUELA', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (3, 0815, 'JUZGADO AGRARIO DEL I CIRCUITO JUDICIAL DE ALAJUELA', 'AG', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (14, 0847, 'JUZGADO CONTRAVENCIONAL DE ATENAS', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (14, 0849, 'JUZGADO DE TRABAJO DE MENOR CUANTÍA DE ATENAS', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (14, 0851, 'JUZGADO DE TRÁNSITO DE ATENAS', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (10, 0860, 'JUZGADO CONTRAVENCIONAL DEL I CIRCUITO JUDICIAL DE LA ZONA ATLÁNTICA', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (15, 0868, 'JUZGADO DE TRABAJO DE NICOYA', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (15, 0872, 'JUZGADO CONTRAVENCIONAL DE NICOYA', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (15, 0874, 'JUZGADO DE TRABAJO DE MENOR CUANTÍA DE NICOYA', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (57, 0876, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE NANDAYURE (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (57, 0878, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE NANDAYURE (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (57, 0880, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE NANDAYURE (TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (72, 0881, 'JUZGADO CONTRAVENCIONAL DE HOJANCHA (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (72, 0883, 'JUZGADO CONTRAVENCIONAL DE HOJANCHA (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (72, 0885, 'JUZGADO CONTRAVENCIONAL DE HOJANCHA (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (66, 0891, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE PAVAS (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (20, 0899, 'JUZGADO DE TRÁNSITO DE GRECIA', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (22, 0912, 'TRIBUNAL DE HEREDIA - SEDE SARAPIQUÍ', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (67, 0917, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE ESCAZÚ (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (16, 0920, 'JUZGADO CIVIL Y TRABAJO DEL II CIRCUITO JUDICIAL DE LA ZONA SUR (CORREDORES) (MATERIA CIVIL)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (44, 0926, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE SAN JOAQUÍN DE FLORES (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (50, 0927, 'JUZGADO CIVIL Y TRABAJO DE CAÑAS (MATERIA CIVIL)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (11, 0929, 'JUZGADO DE TRABAJO DEL II CIRCUITO JUDICIAL DE LA ZONA ATLÁNTICA', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (11, 0930, 'JUZGADO CIVIL DEL II CIRCUITO JUDICIAL DE LA ZONA ATLÁNTICA', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (48, 0934, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE SIQUIRRES (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (7, 0940, 'TRIBUNAL DE APELACIÓN CIVIL Y TRABAJO GUANACASTE (SEDE LIBERIA) (MATERIA CIVIL)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (7, 0941, 'TRIBUNAL DE TRABAJO DE LIBERIA', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (7, 0942, 'JUZGADO DE TRABAJO DE MAYOR CUANTÍA DE LIBERIA', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (7, 0943, 'JUZGADO CONTRAVENCIONAL DE LIBERIA', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (2, 0951, 'TRIBUNAL PENAL DEL II CIRCUITO JUDICIAL DE SAN JOSÉ', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 0958, 'JUZGADO CONCURSAL DE SAN JOSÉ (JUZGADO 5TO CIVIL DE SAN JOSÉ)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (12, 0993, 'JUZGADO AGRARIO DEL III CIRCUITO JUDICIAL DE ALAJUELA (SAN RAMÓN)', 'AG', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (18, 1001, 'JUZGADO DE TRABAJO DE TURRIALBA', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (18, 1002, 'JUZGADO AGRARIO DE TURRIALBA', 'AG', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (18, 1005, 'JUZGADO CONTRAVENCIONAL DE TURRIALBA', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (18, 1007, 'JUZGADO DE TRABAJO DE MENOR CUANTÍA DE TURRIALBA', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (18, 1008, 'JUZGADO DE TRÁNSITO DE TURRIALBA', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 1011, 'TRIBUNAL DE CASACION DE LO CONTENCIOSO ADMINISTRATIVO', 'CA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (2, 1027, 'TRIBUNAL CONTENCIOSO ADMINISTRATIVO DEL II CIRCUITO JUDICIAL DE SAN JOSÉ (CPC)', 'CA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (2, 1028, 'JUZGADO CONTENCIOSO ADMINISTRATIVO Y CIVIL DE HACIENDA DEL II CIRCUITO JUDICIAL DE SAN JOSÉ (CPC)', 'CA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 1044, 'JUZGADO PRIMERO DE COBRO I CIRCUITO JUDICIAL DE SAN JOSÉ', 'CJ', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (49, 1046, 'JUZGADO CIVIL - TRABAJO Y FAMILIA DE BUENOS AIRES (MATERIA CIVIL)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (19, 1085, 'JUZGADO DE TRABAJO DE GOLFITO', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (19, 1097, 'JUZG. CONTRAVENCIONAL DE GOLFITO', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (19, 1099, 'JUZG. TRABAJO DE MENOR CUANTÍA DE GOLFITO', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (19, 1100, 'JUZG. TRÁNSITO DE GOLFITO', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 1102, 'JUZGADO DE SEGURIDAD SOCIAL - I CIRCUITO JUDICIAL DE SAN JOSÉ', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (20, 1113, 'JUZGADO CIVIL Y TRABAJO DE GRECIA (Materia Laboral)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (20, 1116, 'JUZGADO CONTRAVENCIONAL DE GRECIA', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (20, 1118, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE GRECIA (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (2, 1120, 'TRIBUNAL DE APELACIÓNES DE LO CONTENCIOSO ADMINISTRATIVO Y CIVIL DE HACIENDA - SEGUNDO CIRCUITO JUDICIAL - SAN JOSÉ - CALLE BLANCOS', 'CA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (8, 1122, 'TRIBUNAL DE APELACIÓN CIVIL Y DE TRABAJO ZONA SUR (SEDE PÉREZ ZELEDÓN) (MATERIA CIVIL)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (8, 1123, 'TRIBUNAL LABORAL DEL I CIRCUITO JUDICIAL DE LA ZONA SUR (PÉREZ ZELEDÓN)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (8, 1125, 'JUZGADO DE TRABAJO DEL I CIRCUITO JUDICIAL DE LA ZONA SUR (PÉREZ ZELEDÓN)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (8, 1126, 'JUZGADO CONTRAVENCIONAL DEL I CIRCUITO JUDICIAL DE LA ZONA SUR (PÉREZ ZELEDÓN)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (8, 1129, 'JUZGADO AGRARIO DEL I CIRCUITO JUDICIAL DE LA ZONA SUR (PÉREZ ZELEDÓN)', 'AG', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (10, 1140, 'TRIBUNAL DE APELACIÓN CIVIL Y TRABAJO ZONA ATLÁNTICA (SEDE LIMON) (MATERIA CIVIL)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (10, 1141, 'TRIBUNAL LABORAL DE I CIRC. JUD. DE LA ZONA ATLÁNTICA', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (38, 1143, 'JUZGADO CIVIL Y TRABAJO DEL II CIRCUITO JUDICIAL DE ALAJUELA - SEDE UPALA (MATERIA CIVIL)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (6, 1149, 'JUZGADO CONTRAVENCIONAL DE PUNTARENAS', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (3, 1157, 'JUZGADO DE COBRO DEL I CIRCUITO JUDICIAL DE ALAJUELA', 'CJ', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (5, 1158, 'JUZGADO DE COBRO DE HEREDIA', 'CJ', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (9, 1164, 'JUZGADO ESPECIALIZADO DE COBRO DE CARTAGO', 'CJ', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 1170, 'JUZGADO SEGUNDO DE COBRO I CIRCUITO JUDICIAL DE SAN JOSÉ', 'CJ', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 1178, 'JUZGADO DE TRABAJO DEL I CIRCUITO JUDICIAL DE SAN JOSÉ - SECCIÓN PRIMERA', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (8, 1200, 'JUZGADO DE COBRO I CIRCUITO JUDICIAL ZONA SUR (PÉREZ ZELEDÓN)', 'CJ', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (19, 1201, 'JUZGADO DE COBRO DE GOLFITO', 'CJ', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (4, 1202, 'JUZGADO DE COBRO DEL II CIRCUITO JUDICIAL DE ALAJUELA', 'CJ', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (12, 1203, 'JUZGADO DE COBRO DEL III CIRCUITO JUDICIAL DE ALAJUELA (SAN RAMÓN)', 'CJ', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (20, 1204, 'JUZGADO DE COBRO DE GRECIA', 'CJ', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (7, 1205, 'JUZGADO DE COBRO I CIRCUITO JUDICIAL GUANACASTE', 'CJ', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (13, 1206, 'JUZGADO DE COBRO Y TRÁNSITO DEL SEGUNDO CIRCUITO JUDICIAL DE GUANACASTE (MATERIA COBRO)', 'CJ', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (6, 1207, 'JUZGADO DE COBRO DE PUNTARENAS', 'CJ', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (10, 1208, 'JUZGADO DE COBRO DEL I CIRCUITO JUDICIAL ZONA ATLÁNTICA', 'CJ', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (11, 1209, 'JUZGADO DE COBRO DE POCOCI', 'CJ', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (2, 1210, 'TRIBUNAL DE APELACIÓN DE SENTENCIA PENAL DEL II CIRCUITO JUDICIAL DE SAN JOSÉ', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (12, 1211, 'TRIBUNAL DE APELACIÓN DE SENTENCIA PENAL DEL III CIRCUITO JUDICIAL DE ALAJUELA', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (9, 1212, 'TRIBUNAL DE APELACIÓN DE SENTENCIA PENAL DE CARTAGO', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (13, 1213, 'TRIBUNAL DE APELACIÓN DE SENTENCIA PENAL DE GUANACASTE', 'PE', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (4, 1288, 'JUZGADO DE TRABAJO DEL II CIRCUITO JUDICIAL DE ALAJUELA (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (4, 1289, 'JUZGADO CONTRAVENCIONAL DEL II CIRCUITO DE ALAJUELA', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (22, 1309, 'JUZGADO CIVIL - TRABAJO - FAMILIA - PENAL JUVENIL Y VIOLENCIA DOMÉSTICA DE SARAPIQUÍ\~(MATERIA CIVIL)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (22, 1315, 'JUZGADO CONTRAVENCIONAL - MENOR CUANTÍA Y TRÁNSITO DE SARAPIQUÍ (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (21, 1333, 'JUZGADO CONTRAVENCIONAL DE PUERTO JIMENEZ (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (21, 1334, 'JUZGADO DE CONTRAVENCIONES DE GOLFITO - SEDE PUERTO JIMÉNEZ', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (21, 1336, 'JUZGADO DE TRÁNSITO DE GOLFITO - SEDE PUERTO JIMÉNEZ', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 1338, 'JUZGADO TERCERO DE COBRO I CIRCUITO JUDICIAL DE SAN JOSÉ', 'CJ', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (22, 1340, 'JUZGADO CONTRAVENCIONAL - MENOR CUANTÍA Y TRANSITO DE SARAPIQUÍ (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (22, 1341, 'JUZGADO CONTRAVENCIONAL - MENOR CUANTÍA Y TRÁNSITO DE SARAPIQUÍ (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (22, 1342, 'JUZGADO CIVIL - TRABAJO - FAMILIA - PENAL JUVENIL Y VIOLENCIA DOMÉSTICA DE SARAPIQUÍ (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (25, 1418, 'JUZGADO DE TRABAJO - II CIRCUITO JUDICIAL ZONA SUR (OSA)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (25, 1423, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE OSA (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (25, 1424, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE OSA (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (25, 1425, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE OSA (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (16, 1428, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DEL II CIRCUITO JUDICIAL DE LA ZONA SUR (CORREDORES) (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (16, 1429, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DEL II CIRCUITO JUDICIAL DE LA ZONA SUR (CORREDORES) (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (16, 1430, 'JUZGADO CIVIL Y TRABAJO DEL II CIRCUITO JUDICIAL DE LA ZONA SUR (CORREDORES) (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (26, 1439, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE COTO BRUS (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (26, 1441, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE COTO BRUS (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (26, 1443, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE DE COTO BRUS (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (27, 1444, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE ALVARADO (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (27, 1446, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE ALVARADO (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (27, 1448, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE ALVARADO (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (24, 1449, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE LA UNIÓN (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (24, 1450, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE LA UNIÓN (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (28, 1451, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE TARRAZÚ - DOTA Y LEÓN CORTÉS (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (28, 1453, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE TARRAZÚ - DOTA Y LEÓN CORTÉS (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (28, 1455, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE TARRAZÚ - DOTA Y LEÓN CORTÉS (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (29, 1456, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE PARAÍSO (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (29, 1458, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE PARAÍSO (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (30, 1460, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE JIMÉNEZ (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (30, 1462, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE JIMÉNEZ (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (30, 1464, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE JIMÉNEZ (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (31, 1465, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE SAN MATEO (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (31, 1467, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE SAN MATEO (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (31, 1469, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE SAN MATEO (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (32, 1470, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE OROTINA (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (32, 1472, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE OROTINA (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (33, 1474, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE POÁS (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (33, 1476, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE POÁS (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (33, 1478, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE POÁS (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (34, 1479, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE VALVERDE VEGA (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (34, 1481, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE VALVERDE VEGA (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (35, 1483, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE PALMARES (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (35, 1485, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE PALMARES  (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (36, 1487, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE NARANJO (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (36, 1489, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE NARANJO (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (37, 1491, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE ZARCERO (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (37, 1493, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE ZARCERO (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (37, 1495, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE ZARCERO (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (38, 1496, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE UPALA (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (38, 1498, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE UPALA (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (38, 1500, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE UPALA (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (39, 1501, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE LOS CHILES (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (39, 1503, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE LOS CHILES (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (39, 1505, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE LOS CHILES (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (40, 1506, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE GUATUSO (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (40, 1508, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE GUATUSO (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (40, 1510, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE GUATUSO (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (41, 1511, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE LA FORTUNA (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (41, 1513, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE LA FORTUNA (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (41, 1515, 'JUZGADO CONTRAVENCIONAL Y MENOR CUANTÍA DE LA FORTUNA (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (38, 1516, 'JUZGADO CIVIL Y TRABAJO DEL II CIRCUITO JUDICIAL DE ALAJUELA - SEDE UPALA (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (38, 1520, 'JUZGADO CIVIL Y TRABAJO DEL II CIRCUITO JUDICIAL DE ALAJUELA - SEDE UPALA (MATERIA AGRARIA)', 'AG', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 1527, 'TRIBUNAL DE APELACIÓN DE TRABAJO DEL PRIMER CIRCUITO JUDICIAL DE SAN JOSÉ', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (45, 1529, 'JUZGADO CIVIL - TRABAJO Y FAMILIA DE PURISCAL (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (62, 1533, 'JUZGADO CIVIL - TRABAJO Y FAMILIA DE HATILLO - SAN SEBASTIÁN Y ALAJUELITA (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (46, 1535, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE BRIBRÍ (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (46, 1537, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE BRIBRÍ (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (46, 1539, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE BRIBRÍ (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (47, 1540, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE MATINA (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (47, 1542, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE MATINA (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (58, 1544, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE GUÁCIMO (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (58, 1546, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE GUÁCIMO (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (48, 1549, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE SIQUIRRES (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (17, 1550, 'JUZGADO CIVIL Y TRABAJO DEL III CIRCUITO JUDICIAL DE SAN JOSÉ (DESAMPARADOS) (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (49, 1551, 'JUZGADO CIVIL - TRABAJO Y FAMILIA DE BUENOS AIRES (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (49, 1555, 'JUZGADO CIVIL - TRABAJO Y FAMILIA DE BUENOS AIRES (MATERIA AGRARIA)', 'AG', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (50, 1557, 'JUZGADO CIVIL Y TRABAJO DE CAÑAS (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (51, 1558, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE BAGACES (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (51, 1560, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE BAGACES (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (51, 1561, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE BAGACES (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (52, 1562, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE LA CRUZ (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (52, 1564, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE LA CRUZ (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (52, 1566, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE LA CRUZ (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (53, 1567, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE TILARÁN (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (53, 1569, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE TILARÁN (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (53, 1571, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE TILARÁN (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (54, 1572, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE ABANGARES (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (54, 1574, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE ABANGARES (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (54, 1576, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE ABANGARES (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (55, 1577, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE JICARAL (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (55, 1579, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE JICARAL (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (55, 1581, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE JICARAL (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (56, 1582, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE CARRILLO (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (56, 1584, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE CARRILLO (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (56, 1586, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE CARRILLO (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (6, 1587, 'JUZGADO CIVIL Y AGRARIO DE PUNTARENAS (MATERIA AGRARIA)', 'AG', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (6, 1588, 'TRIBUNAL DE APELACIÓN CIVIL Y TRABAJO PUNTARENAS (SEDE PUNTARENAS) (MATERIA CIVIL)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (6, 1589, 'TRIBUNAL DE PUNTARENAS (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (43, 1590, 'JUZGADO CIVIL Y DE TRABAJO DE QUEPOS\~ (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (42, 1594, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE GARABITO (MATERIA CONTRAVENCIONAL)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (42, 1596, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE GARABITO\~ (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (42, 1598, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE GARABITO (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (59, 1599, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE CÓBANO (MATERIA CONTRAVENCIONAL )', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (59, 1601, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE CÓBANO\~ (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (59, 1603, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE CÓBANO (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (60, 1604, 'JUZGADO CONTRAVENCIONAL DE MONTEVERDE (MATERIA CONTRAVENCIONAL )', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (60, 1606, 'JUZGADO CONTRAVENCIONAL DE MONTEVERDE\~ (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (60, 1608, 'JUZGADO CONTRAVENCIONAL DE MONTEVERDE (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 1623, 'TRIBUNAL PRIMERO COLEGIADO PRIMERA INSTANCIA CIVIL I CIRCUITO JUDICIAL SAN JOSÉ', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (1, 1624, 'TRIBUNAL SEGUNDO COLEGIADO PRIMERA INSTANCIA CIVIL I CIRCUITO JUDICIAL SAN JOSÉ', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (62, 1625, 'TRIBUNAL COLEGIADO PRIMERA INSTANCIA CIVIL III CIRCUITO JUD. SAN JOSÉ (HATILLO)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (3, 1626, 'TRIBUNAL COLEGIADO PRIMERA INSTANCIA CIVIL I CIRCUITO JUD. ALAJUELA', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (12, 1627, 'TRIBUNAL COLEGIADO PRIMERA INSTANCIA CIVIL III CIRCUITO JUD. ALAJUELA (SAN RAMÓN)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (9, 1629, 'TRIBUNAL COLEGIADO PRIMERA INSTANCIA CIVIL CARTAGO', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (5, 1630, 'TRIBUNAL COLEGIADO PRIMERA INSTANCIA CIVIL HEREDIA', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (7, 1631, 'TRIBUNAL COLEGIADO PRIMERA INSTANCIA CIVIL I CIRCUITO JUD. GUANACASTE (LIBERIA)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (15, 1632, 'TRIBUNAL COLEGIADO PRIMERA INSTANCIA CIVIL II CIRCUITO JUD. GUANACASTE (NICOYA)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (6, 1633, 'TRIBUNAL COLEGIADO PRIMERA INSTANCIA CIVIL PUNTARENAS', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (8, 1634, 'TRIBUNAL COLEGIADO PRIMERA INSTANCIA CIVIL I CIRCUITO JUD. ZONA SUR (PÉREZ ZELEDÓN)', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (10, 1636, 'TRIBUNAL COLEGIADO PRIMERA INSTANCIA CIVIL I CIRCUITO JUD. ZONA ATLÁNTICA', 'CI', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (62, 1689, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE HATILLO (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (62, 1691, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE HATILLO (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (63, 1692, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE MORA (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (63, 1694, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE MORA (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (63, 1696, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE MORA (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (64, 1697, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE ASERRÍ (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (64, 1699, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE ASERRÍ (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (45, 1701, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE PURISCAL (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (45, 1703, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE PURISCAL (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (45, 1704, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE PURISCAL (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (65, 1705, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE ACOSTA (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (65, 1707, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE ACOSTA (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (65, 1709, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE ACOSTA (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (61, 1710, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE TURRUBARES (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (61, 1712, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE TURRUBARES (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (61, 1714, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE TURRUBARES (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (62, 1715, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE SAN SEBASTIÁN (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (62, 1717, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE SAN SEBASTIÁN (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (62, 1718, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE ALAJUELITA (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (62, 1720, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE ALAJUELITA (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (66, 1722, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE PAVAS (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (67, 1724, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE ESCAZÚ (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (68, 1725, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE SANTA ANA (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (68, 1727, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE SANTA ANA (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (68, 1729, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE SANTA ANA (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (69, 1730, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE ESPARZA (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (70, 1733, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE MONTES DE ORO (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (49, 1736, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE BUENOS AIRES (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (49, 1738, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE BUENOS AIRES (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (49, 1739, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE BUENOS AIRES (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (43, 1740, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE QUEPOS (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (43, 1742, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE QUEPOS (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (43, 1743, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE QUEPOS (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (71, 1744, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE PARRITA (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (71, 1746, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE PARRITA (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (71, 1748, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE PARRITA (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (50, 1749, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE CAÑAS (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (50, 1751, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE CAÑAS (MATERIA LABORAL)', 'LA', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (50, 1752, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE CAÑAS (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (73, 1753, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE SANTO DOMINGO (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (73, 1756, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE SANTO DOMINGO (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (74, 1757, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE SAN ISIDRO (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (74, 1760, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE SAN ISIDRO (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (2, 1763, 'JUZGADO ESPECIALIZADO DE COBRO II CIRCUITO JUDICIAL DE SAN JOSÉ - SECCIÓN PRIMERA', 'CJ', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (2, 1764, 'JUZGADO ESPECIALIZADO DE COBRO II CIRCUITO JUDICIAL DE SAN JOSÉ - SECCIÓN SEGUNDA', 'CJ', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (2, 1765, 'JUZGADO ESPECIALIZADO DE COBRO II CIRCUITO JUDICIAL DE SAN JOSÉ - SECCIÓN TERCERA', 'CJ', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (75, 1778, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE SAN RAFAEL (MATERIA FALTAS Y CONTRAVENCIONES)', 'FC', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (75, 1781, 'JUZGADO CONTRAVENCIONAL Y DE MENOR CUANTÍA DE SAN RAFAEL (MATERIA TRÁNSITO)', 'TR', USER)
   INTO office(judicial_circuit_id, id, name, subject_code, creation_user) VALUES (7, 1815, 'JUZGADO DE TRÁNSITO DE LIBERIA', 'TR', USER)
SELECT * FROM DUAL;