INSERT ALL
    INTO type_of_record(id, description, creation_user) VALUES (1,'AGRAVIO', USER)
    INTO type_of_record(id, description, creation_user) VALUES (2,'ARBITRAL', USER)
    INTO type_of_record(id, description, creation_user) VALUES (3,'CONTENCIOSO ADMINISTRATIVO', USER)
    INTO type_of_record(id, description, creation_user) VALUES (4,'CIVIL', USER)
    INTO type_of_record(id, description, creation_user) VALUES (5,'COBRO JUDICIAL', USER)
    INTO type_of_record(id, description, creation_user) VALUES (6,'FALTAS Y CONTRAVENCIONES', USER)
    INTO type_of_record(id, description, creation_user) VALUES (7,'LABORAL', USER)
    INTO type_of_record(id, description, creation_user) VALUES (8,'NOTARIADO', USER)
    INTO type_of_record(id, description, creation_user) VALUES (9,'OTRAS', USER)
    INTO type_of_record(id, description, creation_user) VALUES (10,'PENSIONES ALIMENTARIAS', USER)
    INTO type_of_record(id, description, creation_user) VALUES (11,'PENAL', USER)
    INTO type_of_record(id, description, creation_user) VALUES (12,'SALA PRIMERA', USER)
    INTO type_of_record(id, description, creation_user) VALUES (13,'TRÁNSITO', USER)
SELECT * FROM DUAL;