-- DATA TABLESPACE
CREATE TABLESPACE AD_DATA
    DATAFILE 'D:\app\kenne\oradata\JUDICIALRECORDSYSTEM\ad_data01.dbf'
    SIZE 10M
    REUSE
    AUTOEXTEND ON
    NEXT 512k
    MAXSIZE 200M;
    
-- INDEX TABLESPACE
CREATE TABLESPACE AD_INDEX
    DATAFILE 'D:\app\kenne\oradata\JUDICIALRECORDSYSTEM\ad_index01.dbf'
    SIZE 10M
    REUSE
    AUTOEXTEND ON
    NEXT 512k
    MAXSIZE 200M;