-- CREATION OF USER
CREATE USER ad
    IDENTIFIED BY ad
    DEFAULT TABLESPACE ad_data
    QUOTA 10M ON ad_data
    TEMPORARY TABLESPACE temp
    QUOTA 5M ON system;
    
-- PERMISSIONS
    GRANT CONNECT TO ad;
    GRANT CREATE SESSION TO ad;
    GRANT CREATE TABLE TO ad;