CREATE OR REPLACE PACKAGE LogInSystem AS
    
    -- CHECKS DATA OF THE USER AND RETURNS ITS ID IF FOUND
    FUNCTION login (pUsername VARCHAR2, pPassword VARCHAR2)
    RETURN NUMBER; 
    
    -- INSERTS A USER INTO THE DATABASE
    PROCEDURE signup (pUsername VARCHAR2, pPassword VARCHAR2);
    
    -- CHANGES THE PASSWORD OF A USER, INTENDED TO BE USED BY A USER
    PROCEDURE changePasswordAsUser (pUsername VARCHAR2, pOldPassword VARCHAR2, pNewPassword VARCHAR2);
    
    -- CHANGES THE PASSWORD OF A USER, 
    -- INTENDED TO BE USED BY AN ADMINISTRATOR
    -- TO CHANGE ANY PASSWORD
    PROCEDURE changePasswordAsAdmin (pUsername VARCHAR2, pNewPassword VARCHAR2);
    
    -- VERIFIES IF THE USER IS ACTUALLY THE ONE USING THE ACCOUNT
    -- INTENDED TO BE USED WHEN MANAGING INFORMATION (PRIVACY)
    FUNCTION verifyUser (pId NUMBER, pPassword VARCHAR2)
    RETURN NUMBER;
    
END LogInSystem;
/


