CREATE OR REPLACE PACKAGE userdata AS
    
    -- GETS THE USERNAME OF A SPECIFIC USER
    FUNCTION getUsername (pId NUMBER)
    RETURN VARCHAR2;

    -- GETS THE PASSWORD OF A SPECIFIC USER
    FUNCTION getPassword (pId NUMBER)
    RETURN VARCHAR2;

    -- CHANGES THE PASSWORD OF A USER, INTENDED TO BE USED BY A USER
    PROCEDURE changePasswordAsUser (pUsername VARCHAR2, pOldPassword VARCHAR2, pNewPassword VARCHAR2);
    
    -- CHANGES THE PASSWORD OF A USER, 
    -- INTENDED TO BE USED BY AN ADMINISTRATOR
    -- TO CHANGE ANY PASSWORD
    PROCEDURE changePasswordAsAdmin (pUsername VARCHAR2, pNewPassword VARCHAR2);
    
    -- VERIFIES IF THE USER IS ACTUALLY THE ONE USING THE ACCOUNT
    -- INTENDED TO BE USED WHEN MANAGING INFORMATION (PRIVACY)
    FUNCTION verifyUser (pId NUMBER, pPassword VARCHAR2)
    RETURN NUMBER;
    
    -- CHECKS IF A USER IS AN ADMIN
    FUNCTION isAdmin (pId NUMBER)
    RETURN NUMBER;

END userdata;
/
