-- DATA TABLESPACE
CREATE TABLESPACE AD_DATA
    DATAFILE 'D:\app\kenne\oradata\DBPRUEBA\addata01.dbf'
    SIZE 10M
    REUSE
    AUTOEXTEND ON
    NEXT 512k
    MAXSIZE 200M;
    
-- INDEX TABLESPACE
CREATE TABLESPACE AD_INDEX
    DATAFILE 'D:\app\kenne\oradata\DBPRUEBA\adindex01.dbf'
    SIZE 10M
    REUSE
    AUTOEXTEND ON
    NEXT 512k
    MAXSIZE 200M;