INSERT ALL
   INTO judicial_circuit(id, description_, canton_id) VALUES (9, 'CIRCUITO JUDICIAL DE CARTAGO', 301)
   INTO judicial_circuit(id, description_, canton_id) VALUES (27, 'CIRCUITO JUDICIAL DE CARTAGO (ALVARADO)', 306)
   INTO judicial_circuit(id, description_, canton_id) VALUES (30, 'CIRCUITO JUDICIAL DE CARTAGO (JIMÉNEZ)', 304)
   INTO judicial_circuit(id, description_, canton_id) VALUES (24, 'CIRCUITO JUDICIAL DE CARTAGO (LA UNIÓN)', 303)
   INTO judicial_circuit(id, description_, canton_id) VALUES (29, 'CIRCUITO JUDICIAL DE CARTAGO (PARAÍSO)', 302)
   INTO judicial_circuit(id, description_, canton_id) VALUES (28, 'CIRCUITO JUDICIAL DE CARTAGO (TARRAZÚ, DOTA Y LEÓN CORTÉS)', 105)
   INTO judicial_circuit(id, description_, canton_id) VALUES (5, 'CIRCUITO JUDICIAL DE HEREDIA', 401)
   INTO judicial_circuit(id, description_, canton_id) VALUES (74, 'CIRCUITO JUDICIAL DE HEREDIA (SAN ISIDRO)', 406)
   INTO judicial_circuit(id, description_, canton_id) VALUES (44, 'CIRCUITO JUDICIAL DE HEREDIA (SAN JOAQUÍN)', 408)
   INTO judicial_circuit(id, description_, canton_id) VALUES (75, 'CIRCUITO JUDICIAL DE HEREDIA (SAN RAFAEL)', 405)
   INTO judicial_circuit(id, description_, canton_id) VALUES (73, 'CIRCUITO JUDICIAL DE HEREDIA (SANTO DOMINGO)', 403)
   INTO judicial_circuit(id, description_, canton_id) VALUES (22, 'CIRCUITO JUDICIAL DE HEREDIA (SARAPIQUÍ)', 410)
   INTO judicial_circuit(id, description_, canton_id) VALUES (6, 'CIRCUITO JUDICIAL DE PUNTARENAS', 601)
   INTO judicial_circuit(id, description_, canton_id) VALUES (59, 'CIRCUITO JUDICIAL DE PUNTARENAS (CÓBANO)', 601)
   INTO judicial_circuit(id, description_, canton_id) VALUES (69, 'CIRCUITO JUDICIAL DE PUNTARENAS (ESPARZA)', 602)
   INTO judicial_circuit(id, description_, canton_id) VALUES (42, 'CIRCUITO JUDICIAL DE PUNTARENAS (GARABITO)', 611)
   INTO judicial_circuit(id, description_, canton_id) VALUES (70, 'CIRCUITO JUDICIAL DE PUNTARENAS (MONTES DE ORO - MIRAMAR)', 504)
   INTO judicial_circuit(id, description_, canton_id) VALUES (60, 'CIRCUITO JUDICIAL DE PUNTARENAS (MONTEVERDE)', 601)
   INTO judicial_circuit(id, description_, canton_id) VALUES (71, 'CIRCUITO JUDICIAL DE PUNTARENAS (PARRITA)', 609)
   INTO judicial_circuit(id, description_, canton_id) VALUES (43, 'CIRCUITO JUDICIAL DE PUNTARENAS (QUEPOS)', 606)
   INTO judicial_circuit(id, description_, canton_id) VALUES (18, 'CIRCUITO JUDICIAL DE TURRIALBA', 305)
   INTO judicial_circuit(id, description_, canton_id) VALUES (47, 'I CIRCUITO DE LA ZONA ATLÁNTICA (BATÁN-MATINA)', 705)
   INTO judicial_circuit(id, description_, canton_id) VALUES (46, 'I CIRCUITO DE LA ZONA ATLÁNTICA (BRIBRÍ)', 704)
   INTO judicial_circuit(id, description_, canton_id) VALUES (10, 'I CIRCUITO DE LA ZONA ATLANTICA (LIMON)', 701)
   INTO judicial_circuit(id, description_, canton_id) VALUES (3, 'I CIRCUITO JUDICIAL DE ALAJUELA', 201)
   INTO judicial_circuit(id, description_, canton_id) VALUES (14, 'I CIRCUITO JUDICIAL DE ALAJUELA (ATENAS)', 205)
   INTO judicial_circuit(id, description_, canton_id) VALUES (32, 'I CIRCUITO JUDICIAL DE ALAJUELA (OROTINA)', 209)
   INTO judicial_circuit(id, description_, canton_id) VALUES (33, 'I CIRCUITO JUDICIAL DE ALAJUELA (PÓAS)', 208)
   INTO judicial_circuit(id, description_, canton_id) VALUES (31, 'I CIRCUITO JUDICIAL DE ALAJUELA (SAN MATEO)', 204)
   INTO judicial_circuit(id, description_, canton_id) VALUES (54, 'I CIRCUITO JUDICIAL DE GUANACASTE (ABANGARES)', 507)
   INTO judicial_circuit(id, description_, canton_id) VALUES (51, 'I CIRCUITO JUDICIAL DE GUANACASTE (BAGACES)', 504)
   INTO judicial_circuit(id, description_, canton_id) VALUES (50, 'I CIRCUITO JUDICIAL DE GUANACASTE (CAÑAS)', 506)
   INTO judicial_circuit(id, description_, canton_id) VALUES (52, 'I CIRCUITO JUDICIAL DE GUANACASTE (LA CRUZ)', 510)
   INTO judicial_circuit(id, description_, canton_id) VALUES (7, 'I CIRCUITO JUDICIAL DE GUANACASTE (LIBERIA)', 501)
   INTO judicial_circuit(id, description_, canton_id) VALUES (53, 'I CIRCUITO JUDICIAL DE GUANACASTE (TILARAN)', 508)
   INTO judicial_circuit(id, description_, canton_id) VALUES (49, 'I CIRCUITO JUDICIAL DE LA ZONA SUR (BUENOS AIRES)', 603)
   INTO judicial_circuit(id, description_, canton_id) VALUES (8, 'I CIRCUITO JUDICIAL DE LA ZONA SUR (PEREZ ZELEDON)', 119)
   INTO judicial_circuit(id, description_, canton_id) VALUES (1, 'I CIRCUITO JUDICIAL DE SAN JOSE', 101)
   INTO judicial_circuit(id, description_, canton_id) VALUES (45, 'I CIRCUITO JUDICIAL DE SAN JOSÉ (PURISCAL)', 104)
   INTO judicial_circuit(id, description_, canton_id) VALUES (61, 'I CIRCUITO JUDICIAL DE SAN JOSÉ (TURRUBARES)', 116)
   INTO judicial_circuit(id, description_, canton_id) VALUES (58, 'II CIRCUITO DE LA ZONA ATLÁNTICA (GUÁCIMO)', 706)
   INTO judicial_circuit(id, description_, canton_id) VALUES (11, 'II CIRCUITO DE LA ZONA ATLÁNTICA (POCOCI)', 702)
   INTO judicial_circuit(id, description_, canton_id) VALUES (48, 'II CIRCUITO DE LA ZONA ATLÁNTICA (SIQUIRRES)', 703)
   INTO judicial_circuit(id, description_, canton_id) VALUES (40, 'II CIRCUITO JUDICIAL DE ALAJUELA (GUATUSO)', 215)
   INTO judicial_circuit(id, description_, canton_id) VALUES (41, 'II CIRCUITO JUDICIAL DE ALAJUELA (LA FORTUNA)', 210)
   INTO judicial_circuit(id, description_, canton_id) VALUES (39, 'II CIRCUITO JUDICIAL DE ALAJUELA (LOS CHILES)', 214)
   INTO judicial_circuit(id, description_, canton_id) VALUES (4, 'II CIRCUITO JUDICIAL DE ALAJUELA (SAN CARLOS)', 210)
   INTO judicial_circuit(id, description_, canton_id) VALUES (38, 'II CIRCUITO JUDICIAL DE ALAJUELA (UPALA)', 213)
   INTO judicial_circuit(id, description_, canton_id) VALUES (56, 'II CIRCUITO JUDICIAL DE GUANACASTE (CARILLO)', 505)
   INTO judicial_circuit(id, description_, canton_id) VALUES (72, 'II CIRCUITO JUDICIAL DE GUANACASTE (HOJANCHA)', 511)
   INTO judicial_circuit(id, description_, canton_id) VALUES (55, 'II CIRCUITO JUDICIAL DE GUANACASTE (JICARAL)', 601)
   INTO judicial_circuit(id, description_, canton_id) VALUES (57, 'II CIRCUITO JUDICIAL DE GUANACASTE (NANDAYURE)', 509)
   INTO judicial_circuit(id, description_, canton_id) VALUES (15, 'II CIRCUITO JUDICIAL DE GUANACASTE (NICOYA)', 502)
   INTO judicial_circuit(id, description_, canton_id) VALUES (13, 'II CIRCUITO JUDICIAL DE GUANACASTE (SANTA CRUZ)', 503)
   INTO judicial_circuit(id, description_, canton_id) VALUES (16, 'II CIRCUITO JUDICIAL DE LA ZONA SUR (CORREDORES)', 610)
   INTO judicial_circuit(id, description_, canton_id) VALUES (26, 'II CIRCUITO JUDICIAL DE LA ZONA SUR (COTO BRUS)', 608)
   INTO judicial_circuit(id, description_, canton_id) VALUES (19, 'II CIRCUITO JUDICIAL DE LA ZONA SUR (GOLFITO)', 607)
   INTO judicial_circuit(id, description_, canton_id) VALUES (21, 'II CIRCUITO JUDICIAL DE LA ZONA SUR (GOLFITO) (PUERTO JIMÉNEZ)', 607)
   INTO judicial_circuit(id, description_, canton_id) VALUES (25, 'II CIRCUITO JUDICIAL DE LA ZONA SUR (OSA)', 605)
   INTO judicial_circuit(id, description_, canton_id) VALUES (2, 'II CIRCUITO JUDICIAL DE SAN JOSE (GOICOECHEA)', 108)
   INTO judicial_circuit(id, description_, canton_id) VALUES (20, 'III CIRCUITO JUDICIAL DE ALAJUELA (GRECIA)', 203)
   INTO judicial_circuit(id, description_, canton_id) VALUES (36, 'III CIRCUITO JUDICIAL DE ALAJUELA (NARANJO)', 206)
   INTO judicial_circuit(id, description_, canton_id) VALUES (35, 'III CIRCUITO JUDICIAL DE ALAJUELA (PALMARES)', 207)
   INTO judicial_circuit(id, description_, canton_id) VALUES (12, 'III CIRCUITO JUDICIAL DE ALAJUELA (SAN RAMON)', 202)
   INTO judicial_circuit(id, description_, canton_id) VALUES (34, 'III CIRCUITO JUDICIAL DE ALAJUELA (SARCHÁ)', 212)
   INTO judicial_circuit(id, description_, canton_id) VALUES (37, 'III CIRCUITO JUDICIAL DE ALAJUELA (ZARCERO)', 211)
   INTO judicial_circuit(id, description_, canton_id) VALUES (65, 'III CIRCUITO JUDICIAL DE SAN JOSÉ (ACOSTA)', 112)
   INTO judicial_circuit(id, description_, canton_id) VALUES (64, 'III CIRCUITO JUDICIAL DE SAN JOSÉ (ASERRÁ)', 106)
   INTO judicial_circuit(id, description_, canton_id) VALUES (17, 'III CIRCUITO JUDICIAL DE SAN JOSÉ (DESAMPARADOS)', 103)
   INTO judicial_circuit(id, description_, canton_id) VALUES (67, 'III CIRCUITO JUDICIAL DE SAN JOSÉ (ESCAZÚ)', 102)
   INTO judicial_circuit(id, description_, canton_id) VALUES (62, 'III CIRCUITO JUDICIAL DE SAN JOSÉ (HATILLO, SAN SEBASTIÁN Y ALAJUELITA)', 101)
   INTO judicial_circuit(id, description_, canton_id) VALUES (63, 'III CIRCUITO JUDICIAL DE SAN JOSÉ (MORA)', 107)
   INTO judicial_circuit(id, description_, canton_id) VALUES (66, 'III CIRCUITO JUDICIAL DE SAN JOSÉ (PAVAS)', 101)
   INTO judicial_circuit(id, description_, canton_id) VALUES (68, 'III CIRCUITO JUDICIAL DE SAN JOSÉ (SANTA ANA)', 109)
SELECT * FROM DUAL;