INSERT ALL
    INTO type_of_record(id, description) VALUES (1,'AGRAVIO')
    INTO type_of_record(id, description) VALUES (2,'ARBITRAL')
    INTO type_of_record(id, description) VALUES (3,'CONTENCIOSO ADMINISTRATIVO')
    INTO type_of_record(id, description) VALUES (4,'CIVIL')
    INTO type_of_record(id, description) VALUES (5,'COBRO JUDICIAL')
    INTO type_of_record(id, description) VALUES (6,'FALTAS Y CONTRAVENCIONES')
    INTO type_of_record(id, description) VALUES (7,'LABORAL')
    INTO type_of_record(id, description) VALUES (8,'NOTARIADO')
    INTO type_of_record(id, description) VALUES (9,'OTRAS')
    INTO type_of_record(id, description) VALUES (10,'PENSIONES ALIMENTARIAS')
    INTO type_of_record(id, description) VALUES (11,'PENAL')
    INTO type_of_record(id, description) VALUES (12,'SALA PRIMERA')
    INTO type_of_record(id, description) VALUES (13,'TRÁNSITO')
SELECT * FROM DUAL;