INSERT ALL
    INTO type_of_record(description) VALUES ('GRIEVANCE')
    INTO type_of_record(description) VALUES ('ARBITRAL')
    INTO type_of_record(description) VALUES ('ADMINISTRATIVE LITIGATION')
    INTO type_of_record(description) VALUES ('CIVIL')
    INTO type_of_record(description) VALUES ('JUDICIAL RECOVERY')
    INTO type_of_record(description) VALUES ('OFFENSES AND CONTRAVENTIONS')
    INTO type_of_record(description) VALUES ('LABOR')
    INTO type_of_record(description) VALUES ('NOTARY')
    INTO type_of_record(description) VALUES ('ALIMONY')
    INTO type_of_record(description) VALUES ('PENAL')
    INTO type_of_record(description) VALUES ('SALA PRIMERA')
    INTO type_of_record(description) VALUES ('TRANSIT')
    INTO type_of_record(description) VALUES ('OTHERS')
SELECT * FROM DUAL;