-- PRIMARY KEYS
ALTER TABLE type_of_crime
    ADD CONSTRAINT type_crime_id_pk PRIMARY KEY(id)
    USING INDEX
    TABLESPACE ge_index PCTFREE 20
    STORAGE (INITIAL 10k NEXT 10k PCTINCREASE 0);
    
-- FOREIGN KEYS
