CREATE OR REPLACE PACKAGE userdata AS
    
    -- GETS THE USERNAME OF A SPECIFIC USER
    FUNCTION getUsername (pId NUMBER)
    RETURN VARCHAR2;

    -- GETS THE PASSWORD OF A SPECIFIC USER
    FUNCTION getPassword (pId NUMBER)
    RETURN VARCHAR2;
    
    -- GETS THE ID OF A SPECIFIC USER
    FUNCTION getUserId (pUsername VARCHAR2)
    RETURN NUMBER;

    -- CHECKS IF A USER IS AN ADMIN
    FUNCTION isAdmin (pId NUMBER)
    RETURN NUMBER;

    FUNCTION getPersonFromAccount (pId NUMBER)
    RETURN NUMBER;

END userdata;
/
