# Type of instruction constants
PROCEDURE = 1
FUNCTION = 2

# Package instruction constants (ADMIN QUERIES)
MODIFIED_PASSWORDS = 'ADMIN_QUERIES.GETMODIFIEDPASSWORDS'
NEW_RECORDS = 'ADMIN_QUERIES.GETNEWRECORDS'
UNMODIFIED_PASSWORDS = 'ADMIN_QUERIES.GETUNMODIFIEDPASSWORDS'
UNRESOLVED_RECORDS = 'ADMIN_QUERIES.GETUNRESOLVEDRECORDS'
AVERAGE_RECORDS = 'ADMIN_QUERIES.AVERAGERESOLUTIONTIME'