# Type of instruction constants
PROCEDURE = 1
FUNCTION = 2

# Package instruction constants (ADMIN QUERIES)
MODIFIED_PASSWORDS = 'ADMIN_QUERIES.GETMODIFIEDPASSWORDS'
NEW_RECORDS = 'ADMIN_QUERIES.GETNEWRECORDS'
UNMODIFIED_PASSWORDS = 'ADMIN_QUERIES.GETUNMODIFIEDPASSWORDS'
UNRESOLVED_RECORDS = 'ADMIN_QUERIES.GETUNRESOLVEDRECORDS'
AVERAGE_RECORDS = 'ADMIN_QUERIES.AVERAGERESOLUTIONTIME'

# Package instruction constants (USER QUERIES)
GET_ALL_USERS = 'USER_QUERIES.GETALLUSERS'
GET_BANNED_USERS = 'USER_QUERIES.GETBANNEDUSERS'
GET_COMMITED_CRIMERS = 'USER_QUERIES.GETCOMMITEDCRIMES'
GET_DANGEROUS_CANTONS = 'USER_QUERIES.GETCDANGEROUSCANTONS'
GET_FILTERED_FILES = 'USER_QUERIES.GETFILTEREDFILES'
GET_LONGEST_SENTENCES = 'USER_QUERIES.GETLONGESTSENTENCES'
GET_SOON_TO_EXPIRE = 'USER_QUERIES.GETSOONTOEXPIRE'