-- PRIMARY KEYS
ALTER TABLE office
    ADD CONSTRAINT office_id_pk PRIMARY KEY(id)
    USING INDEX
    TABLESPACE cu_ind PCTFREE 20
    STORAGE (INITIAL 10k NEXT 10k PCTINCREASE 0);
    
-- FOREIGN KEY

