-- PRIMARY KEYS
ALTER TABLE type_of_record
    ADD CONSTRAINT type_record_id_pk PRIMARY KEY(id)
    USING INDEX
    TABLESPACE ge_index PCTFREE 20
    STORAGE (INITIAL 10k NEXT 10k PCTINCREASE 0);
    
-- FOREIGN KEYS
