-- DATA TABLESPACE
CREATE TABLESPACE GE_DATA
    DATAFILE 'D:\app\kenne\oradata\DBPRUEBA\ge_data01.dbf'
    SIZE 10M
    REUSE
    AUTOEXTEND ON
    NEXT 512k
    MAXSIZE 200M;
    
-- INDEX TABLESPACE
CREATE TABLESPACE GE_INDEX
    DATAFILE 'D:\app\kenne\oradata\DBPRUEBA\ge_index01.dbf'
    SIZE 10M
    REUSE
    AUTOEXTEND ON
    NEXT 512k
    MAXSIZE 200M;