-- CREATION OF USER
CREATE USER ge
    IDENTIFIED BY ge
    DEFAULT TABLESPACE ge_data
    QUOTA 10M ON ge_data
    QUOTA 10M ON ge_index
    TEMPORARY TABLESPACE temp
    QUOTA 5M ON system;
    
-- PERMISSIONS
    GRANT CONNECT TO ge;
    GRANT CREATE SESSION TO ge;
    GRANT CREATE TABLE TO ge;
    GRANT CREATE SEQUENCE TO ge;
    GRANT CREATE TRIGGER TO ge;
    GRANT CREATE PROCEDURE TO ge;