# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserHome(object):
    def setupUi(self, UserHome):
        UserHome.setObjectName("UserHome")
        UserHome.resize(1527, 879)
        self.centralwidget = QtWidgets.QWidget(UserHome)
        self.centralwidget.setObjectName("centralwidget")
        self.BackgroundFrame = QtWidgets.QFrame(self.centralwidget)
        self.BackgroundFrame.setGeometry(QtCore.QRect(0, 0, 1531, 861))
        self.BackgroundFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BackgroundFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BackgroundFrame.setObjectName("BackgroundFrame")
        self.BackgroundLabel = QtWidgets.QLabel(self.BackgroundFrame)
        self.BackgroundLabel.setGeometry(QtCore.QRect(0, 0, 1521, 841))
        self.BackgroundLabel.setText("")
        self.BackgroundLabel.setPixmap(QtGui.QPixmap("Images/User-Home.png"))
        self.BackgroundLabel.setScaledContents(True)
        self.BackgroundLabel.setObjectName("BackgroundLabel")
        self.RecordLookUpButton = QtWidgets.QPushButton(self.BackgroundFrame)
        self.RecordLookUpButton.setGeometry(QtCore.QRect(0, 170, 241, 51))
        self.RecordLookUpButton.setText("")
        self.RecordLookUpButton.setFlat(True)
        self.RecordLookUpButton.setObjectName("RecordLookUpButton")
        self.UsernameLabel = QtWidgets.QLabel(self.BackgroundFrame)
        self.UsernameLabel.setGeometry(QtCore.QRect(1390, 20, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(14)
        self.UsernameLabel.setFont(font)
        self.UsernameLabel.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.UsernameLabel.setAutoFillBackground(False)
        self.UsernameLabel.setStyleSheet("color: rgb(234, 234, 234);")
        self.UsernameLabel.setObjectName("UsernameLabel")
        self.GenQueriesButton = QtWidgets.QPushButton(self.BackgroundFrame)
        self.GenQueriesButton.setGeometry(QtCore.QRect(0, 290, 241, 51))
        self.GenQueriesButton.setText("")
        self.GenQueriesButton.setFlat(True)
        self.GenQueriesButton.setObjectName("GenQueriesButton")
        self.PersRegisterButton = QtWidgets.QPushButton(self.BackgroundFrame)
        self.PersRegisterButton.setGeometry(QtCore.QRect(0, 230, 241, 51))
        self.PersRegisterButton.setText("")
        self.PersRegisterButton.setFlat(True)
        self.PersRegisterButton.setObjectName("PersRegisterButton")
        self.RecordRegisterButton = QtWidgets.QPushButton(self.BackgroundFrame)
        self.RecordRegisterButton.setGeometry(QtCore.QRect(0, 120, 241, 51))
        self.RecordRegisterButton.setText("")
        self.RecordRegisterButton.setFlat(True)
        self.RecordRegisterButton.setObjectName("RecordRegisterButton")
        self.HomeButton = QtWidgets.QPushButton(self.BackgroundFrame)
        self.HomeButton.setGeometry(QtCore.QRect(0, 60, 241, 51))
        self.HomeButton.setText("")
        self.HomeButton.setFlat(True)
        self.HomeButton.setObjectName("HomeButton")
        self.LogOutButton = QtWidgets.QPushButton(self.BackgroundFrame)
        self.LogOutButton.setGeometry(QtCore.QRect(0, 780, 241, 51))
        self.LogOutButton.setText("")
        self.LogOutButton.setFlat(True)
        self.LogOutButton.setObjectName("LogOutButton")
        UserHome.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UserHome)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1527, 21))
        self.menubar.setObjectName("menubar")
        UserHome.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UserHome)
        self.statusbar.setObjectName("statusbar")
        UserHome.setStatusBar(self.statusbar)

        self.retranslateUi(UserHome)
        QtCore.QMetaObject.connectSlotsByName(UserHome)

    def retranslateUi(self, UserHome):
        _translate = QtCore.QCoreApplication.translate
        UserHome.setWindowTitle(_translate("UserHome", "Home"))
        self.UsernameLabel.setText(_translate("UserHome", "Username"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserHome = QtWidgets.QMainWindow()
    ui = Ui_UserHome()
    ui.setupUi(UserHome)
    UserHome.show()
    sys.exit(app.exec_())
